# Generated by Django 4.2 on 2023-05-17 16:06

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcabadoPared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de AcabadoPared', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de AcabadoPared', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de Acceso', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de Acceso', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avenida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de la avenida', unique=True)),
                ('nombre', models.TextField(help_text='Nombre de la avenida')),
                ('tipo', models.CharField(choices=[('1', 'Colateral'), ('2', 'Via'), ('3', 'Doble Via')], default='1', help_text='tipo de avenida', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de la calle', unique=True)),
                ('nombre', models.TextField(help_text='Nombre de la calle')),
                ('tipo', models.CharField(choices=[('1', 'Colateral'), ('2', 'Via'), ('3', 'Doble Via')], default='1', help_text='tipo calle', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ConjuntoResidencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(help_text='nombre del conjunto residencial', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de Conservacion', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de Conservacion', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cubierta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de Cubierta', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de Cubierta', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(help_text='nombre del conjunto residencial', unique=True)),
                ('conjunto_residencial', models.ForeignKey(help_text='conjunto residencial asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.conjuntoresidencial')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(help_text='Numero de expediente', unique=True)),
                ('fecha', models.DateTimeField(blank=True, help_text='Fecha Estado Cuenta')),
                ('observaciones', models.TextField(help_text='observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='EstatusInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo del estatus de inmueble', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion del estatus de inmueble', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinesFiscales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de fines fiscales', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de fines fiscales', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de Forma', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de Forma', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expediente', models.TextField(help_text='Numero de expediente', unique=True)),
                ('fecha_inscripcion', models.DateTimeField(blank=True, help_text='fecha de inscripcion')),
                ('numero_civico', models.TextField(help_text='Numero de expediente')),
                ('numero_casa', models.TextField(help_text='Numero de expediente')),
                ('numero_piso', models.TextField(help_text='Numero de expediente')),
                ('telefono', models.TextField(help_text='Numero de expediente')),
                ('direccion', models.TextField(help_text='direccion')),
                ('referencia', models.TextField(help_text='referencia')),
                ('observaciones', models.TextField(help_text='observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleConstruccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_construccion', models.PositiveIntegerField(default=0, help_text='anio_construccion')),
                ('anio_refaccion', models.PositiveIntegerField(default=0, help_text='anio_refaccion')),
                ('porcentaje_refaccion', models.TextField(help_text='Numero de expediente')),
                ('edad_efectiva', models.TextField(help_text='edad_efectiva')),
                ('numero_niveles', models.PositiveIntegerField(default=0, help_text='Numero de niveles')),
                ('numero_edificaciones', models.PositiveIntegerField(default=0, help_text='numero de edificaciones')),
                ('observaciones', models.TextField(help_text='observaciones')),
                ('acabado_pared', models.ForeignKey(help_text='AcabadoPared asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.acabadopared')),
                ('conservacion', models.ForeignKey(help_text='Conservacion asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.conservacion')),
                ('inmueble', models.ForeignKey(help_text='Id Inmueble asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(help_text='Observaciones')),
                ('forma', models.ForeignKey(help_text='Forma asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.forma')),
                ('inmueble', models.ForeignKey(help_text='Id Inmueble asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='Manzana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de la Manzana', unique=True)),
                ('area', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Area en m2', max_digits=14)),
                ('perimetro', models.TextField(help_text='Perimetro de la manzana')),
            ],
        ),
        migrations.CreateModel(
            name='NivelInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo del nivel de inmueble', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion del nivel de inmueble', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de la Parcela', unique=True)),
                ('area', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Area en m2', max_digits=14)),
                ('perimetro', models.TextField(help_text='Perimetro de la Parcela')),
                ('manzana', models.ForeignKey(help_text='Manzana asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.manzana')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.TextField(help_text='Numero de expediente')),
                ('nacionalidad', models.TextField(help_text='Numero de expediente')),
                ('numero_documento', models.TextField(help_text='Numero de expediente', unique=True)),
                ('nombre', models.TextField(help_text='Numero de expediente')),
                ('telefono_principal', models.TextField(help_text='Numero de expediente')),
                ('telefono_secundario', models.TextField(help_text='Numero de expediente')),
                ('email_principal', models.TextField(help_text='Numero de expediente')),
                ('emaill_secundario', models.TextField(help_text='Numero de expediente')),
            ],
        ),
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de Regimen', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de Regimen', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de Servicio', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de Servicio', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Soporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de Soporte', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de Soporte', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TasaMulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Descripcion', unique=True)),
                ('unidad_tributaria', models.TextField(help_text='Cantidad Unidad tributaria')),
                ('monto_unidad_tributaria', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto Unidad tributaria', max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Techo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de Techo', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de Techo', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDesincorporacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de tipo desincorporacion', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion del tipo de desincorporacion', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo del tipo de documento del inmueble', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion del tipo de documento del inmueble', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo del tipo especial del inmueble', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion del tipo especial del inmueble', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo del tipo de inmueble', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion del tipo de inmueble', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de tipologia', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de tipologia', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de TipoPared', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de TipoPared', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTenencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo del tipo tenecia del inmueble', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion del tenecia especial del inmueble', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de tipo transaccion', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion del tipo de transaccion', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de topografia', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de topografia', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de Ubicacion', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de Ubicacion', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de la unidad del inmueble', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de la unidad del inmueble', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de Uso', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de Uso', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsoConstruccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de UsoConstruccion', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de UsoConstruccion', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de Zona', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de la Zona', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ambito',
            name='descripcion',
            field=models.TextField(help_text='Descripcion del ambito'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='area',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Area en m2', max_digits=14),
        ),
        migrations.AlterField(
            model_name='sector',
            name='descripcion',
            field=models.TextField(help_text='Descripcion del Sector'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='perimetro',
            field=models.TextField(help_text='Descripcion del Sector'),
        ),
        migrations.CreateModel(
            name='Urbanizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(help_text='Nombre de la urbanizacion')),
                ('tipo', models.CharField(choices=[('P', 'Publica'), ('R', 'Privada')], default='P', help_text='tipo de la urbanizacion', max_length=1)),
                ('sector', models.ForeignKey(help_text='Sector asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Torre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(help_text='nombre del conjunto residencial', unique=True)),
                ('conjunto_residencial', models.ForeignKey(help_text='conjunto residencial asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.conjuntoresidencial')),
                ('urbanizacion', models.ForeignKey(help_text='Urbanizacion asociada', on_delete=django.db.models.deletion.PROTECT, to='backend.urbanizacion')),
            ],
        ),
        migrations.CreateModel(
            name='SubParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de la SubParcela', unique=True)),
                ('area', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Area en m2', max_digits=14)),
                ('perimetro', models.TextField(help_text='Perimetro de la SubParcela')),
                ('parcela', models.ForeignKey(help_text='Parcela asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.parcela')),
            ],
        ),
        migrations.AddField(
            model_name='manzana',
            name='sector',
            field=models.ForeignKey(help_text='Sector asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.sector'),
        ),
        migrations.AddField(
            model_name='manzana',
            name='via_este',
            field=models.ForeignKey(help_text='Via cercana este', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manzana_via_este', to='backend.calle'),
        ),
        migrations.AddField(
            model_name='manzana',
            name='via_norte',
            field=models.ForeignKey(help_text='Via cercana norte', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manzana_via_norte', to='backend.calle'),
        ),
        migrations.AddField(
            model_name='manzana',
            name='via_oeste',
            field=models.ForeignKey(help_text='Via cercana oeste', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manzana_via_oeste', to='backend.calle'),
        ),
        migrations.AddField(
            model_name='manzana',
            name='via_sur',
            field=models.ForeignKey(help_text='Via cercana sur', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manzana_via_sur', to='backend.calle'),
        ),
        migrations.CreateModel(
            name='InmuebleValoracionTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Area en m2', max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='valor_unitario', max_digits=14)),
                ('area_factor_ajuste', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Area en m2 del factor de ajuste', max_digits=14)),
                ('valor_ajustado', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Valor Ajustado', max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Valor Total', max_digits=14)),
                ('observaciones', models.TextField(help_text='observaciones')),
                ('fines_fiscales', models.ForeignKey(help_text='fines_fiscales asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.finesfiscales')),
                ('forma_factor_ajuste', models.ForeignKey(help_text='Forma del factor de ajuste', on_delete=django.db.models.deletion.PROTECT, to='backend.forma')),
                ('inmueble', models.ForeignKey(help_text='Id Inmueble asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.inmueble')),
                ('tipologia', models.ForeignKey(help_text='tipologia asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.tipologia')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleValoracionConstruccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(blank=True, help_text='fecha_compra')),
                ('trimestre', models.PositiveIntegerField(default=0, help_text='trimestre')),
                ('anio', models.PositiveIntegerField(default=0, help_text='Numero de expediente')),
                ('area', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Area en m2', max_digits=14)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='valor', max_digits=14)),
                ('depreciacion', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='depreciacion', max_digits=14)),
                ('observaciones', models.TextField(help_text='observaciones')),
                ('inmueble_terreno', models.ForeignKey(help_text='Id inmueble_terreno asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.inmueblevaloracionterreno')),
                ('tipologia', models.ForeignKey(help_text='tipologia asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.tipologia')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lindero_norte', models.TextField(help_text='Numero de expediente')),
                ('lindero_sur', models.TextField(help_text='Numero de expediente')),
                ('lindero_este', models.TextField(help_text='Numero de expediente')),
                ('lindero_oeste', models.TextField(help_text='Numero de expediente')),
                ('imagen_inmueble', models.ImageField(blank=True, help_text='Imagen asociado al pais', null=True, upload_to='media/paises')),
                ('imagen_plano', models.ImageField(blank=True, help_text='Imagen asociado al pais', null=True, upload_to='media/paises')),
                ('imagan_plano_mesura', models.ImageField(blank=True, help_text='Imagen asociado al pais', null=True, upload_to='media/paises')),
                ('g1_norte', models.TextField(help_text='Numero de expediente')),
                ('g1_este', models.TextField(help_text='Numero de expediente')),
                ('g2_norte', models.TextField(help_text='Numero de expediente')),
                ('g2_este', models.TextField(help_text='Numero de expediente')),
                ('g3_norte', models.TextField(help_text='Numero de expediente')),
                ('g3_este', models.TextField(help_text='Numero de expediente')),
                ('g4_norte', models.TextField(help_text='Numero de expediente')),
                ('g4_este', models.TextField(help_text='Numero de expediente')),
                ('g5_norte', models.TextField(help_text='Numero de expediente')),
                ('g5_este', models.TextField(help_text='Numero de expediente')),
                ('g6_norte', models.TextField(help_text='Numero de expediente')),
                ('g6_este', models.TextField(help_text='Numero de expediente')),
                ('g7_norte', models.TextField(help_text='Numero de expediente')),
                ('g7_este', models.TextField(help_text='Numero de expediente')),
                ('g8_norte', models.TextField(help_text='Numero de expediente')),
                ('g8_este', models.TextField(help_text='Numero de expediente')),
                ('inmueble', models.ForeignKey(help_text='Id Inmueble asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleTerrenoUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmueble_terreno', models.ForeignKey(help_text='Inmueble asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.inmuebleterreno')),
                ('uso', models.ForeignKey(help_text='uso asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.uso')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleTerrenoTopografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmueble_terreno', models.ForeignKey(help_text='Inmueble asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.inmuebleterreno')),
                ('topografia', models.ForeignKey(help_text='Topografia asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.topografia')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleTerrenoRegimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmueble_terreno', models.ForeignKey(help_text='Inmueble asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.inmuebleterreno')),
                ('regimen', models.ForeignKey(help_text='regimen asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.regimen')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleTerrenoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceso', models.ForeignKey(help_text='Acceso asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.acceso')),
                ('inmueble_terreno', models.ForeignKey(help_text='Inmueble asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.inmuebleterreno')),
            ],
        ),
        migrations.AddField(
            model_name='inmuebleterreno',
            name='servicios',
            field=models.ForeignKey(help_text='Servicios Asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.servicios'),
        ),
        migrations.AddField(
            model_name='inmuebleterreno',
            name='tenencia',
            field=models.ForeignKey(help_text='tenencia asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.tipotenencia'),
        ),
        migrations.AddField(
            model_name='inmuebleterreno',
            name='ubicacion',
            field=models.ForeignKey(help_text='Ubicacion asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.ubicacion'),
        ),
        migrations.CreateModel(
            name='InmueblePropietarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmueble', models.ForeignKey(help_text='Id Inmueble', on_delete=django.db.models.deletion.PROTECT, to='backend.inmueble')),
                ('propietario', models.ForeignKey(help_text='Id Propietario', on_delete=django.db.models.deletion.PROTECT, to='backend.calle')),
            ],
        ),
        migrations.CreateModel(
            name='InmueblePropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_habitabilidad', models.DateTimeField(blank=True, help_text='fecha_habitabilidad')),
                ('fecha_vigencia', models.DateTimeField(blank=True, help_text='fecha de inscripcion')),
                ('fecha_documento', models.DateTimeField(blank=True, help_text='fecha de inscripcion')),
                ('numero_documento', models.TextField(help_text='Numero de expediente', unique=True)),
                ('matricula_documento', models.TextField(help_text='Numero de expediente')),
                ('anio_folio_documento', models.TextField(help_text='Numero de expediente')),
                ('fecha_terreno', models.DateTimeField(blank=True, help_text='fecha de inscripcion')),
                ('numero_terreno', models.TextField(help_text='Numero de expediente')),
                ('folio_terreno', models.TextField(help_text='Numero de expediente')),
                ('protocolo_terreno', models.TextField(help_text='Numero de expediente')),
                ('tomo_terreno', models.TextField(help_text='Numero de expediente')),
                ('area_terreno', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='area_terreno en m2', max_digits=14)),
                ('valor_terreno', models.TextField(help_text='Numero de expediente')),
                ('fecha_construccion', models.DateTimeField(blank=True, help_text='fecha de inscripcion')),
                ('numero_construccion', models.TextField(help_text='Numero de expediente')),
                ('folio_construccion', models.TextField(help_text='Numero de expediente')),
                ('protocolo_construccion', models.TextField(help_text='Numero de expediente')),
                ('tomo_construccion', models.TextField(help_text='Numero de expediente')),
                ('area_construccion', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='area_construccion en m2', max_digits=14)),
                ('lindero_norte', models.TextField(help_text='Numero de expediente')),
                ('lindero_sur', models.TextField(help_text='Numero de expediente')),
                ('lindero_este', models.TextField(help_text='Numero de expediente')),
                ('lindero_oeste', models.TextField(help_text='Numero de expediente')),
                ('inmueble', models.ForeignKey(help_text='Sector asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.inmueble')),
                ('tipo_documento', models.ForeignKey(help_text='Sector asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.tipodocumento')),
                ('tipo_especial', models.ForeignKey(help_text='Sector asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.tipoespecial')),
                ('tipo_tenencia', models.ForeignKey(help_text='tipo_tenencia asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.tipotenencia')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleFaltante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.TextField(help_text='Numero de expediente')),
                ('doumento_propiedad', models.TextField(help_text='Numero de expediente')),
                ('observaciones', models.TextField(help_text='observaciones')),
                ('inmueble', models.ForeignKey(help_text='Id Inmueble asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleConstruccionTecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmueble_construccion', models.ForeignKey(help_text='Inmueble asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.inmuebleconstruccion')),
                ('techo', models.ForeignKey(help_text='Techo asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.techo')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleConstruccionSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmueble_construccion', models.ForeignKey(help_text='Inmueble asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.inmuebleconstruccion')),
                ('soporte', models.ForeignKey(help_text='Soporte asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.soporte')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleConstruccionCubierta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cubierta', models.ForeignKey(help_text='Cubierta asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.cubierta')),
                ('inmueble_construccion', models.ForeignKey(help_text='Inmueble asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.inmuebleconstruccion')),
            ],
        ),
        migrations.AddField(
            model_name='inmuebleconstruccion',
            name='regimen',
            field=models.ForeignKey(help_text='regimen asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.regimen'),
        ),
        migrations.AddField(
            model_name='inmuebleconstruccion',
            name='tenencia',
            field=models.ForeignKey(help_text='tenencia asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.tipotenencia'),
        ),
        migrations.AddField(
            model_name='inmuebleconstruccion',
            name='tipo',
            field=models.ForeignKey(help_text='TipoInmueble asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.tipoinmueble'),
        ),
        migrations.AddField(
            model_name='inmuebleconstruccion',
            name='tipo_pared',
            field=models.ForeignKey(help_text='TipoPared asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.tipopared'),
        ),
        migrations.AddField(
            model_name='inmuebleconstruccion',
            name='uso_construccion',
            field=models.ForeignKey(help_text='uso_construccion asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.usoconstruccion'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='ambito',
            field=models.ForeignKey(help_text='ambito asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.ambito'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='avenida',
            field=models.ForeignKey(help_text='avenida asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.avenida'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='calle',
            field=models.ForeignKey(help_text='calle asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.calle'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='conjunto_residencial',
            field=models.ForeignKey(help_text='Sector asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.conjuntoresidencial'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='edificio',
            field=models.ForeignKey(help_text='edificio asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.edificio'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='manzana',
            field=models.ForeignKey(help_text='manzana asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.manzana'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='nivel',
            field=models.ForeignKey(help_text='nivel asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.nivelinmueble'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='parcela',
            field=models.ForeignKey(help_text='parcela asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.parcela'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='sector',
            field=models.ForeignKey(help_text='Sector asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.sector'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='status',
            field=models.ForeignKey(help_text='status asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.estatusinmueble'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='subparcela',
            field=models.ForeignKey(help_text='subparcela asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.subparcela'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tipo',
            field=models.ForeignKey(help_text='TipoInmueble asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.tipoinmueble'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='torre',
            field=models.ForeignKey(help_text='Sector asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.torre'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='unidad',
            field=models.ForeignKey(help_text='unidad asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.unidadinmueble'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='urbanizacion',
            field=models.ForeignKey(help_text='urbanizacion', on_delete=django.db.models.deletion.PROTECT, to='backend.urbanizacion'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='zona',
            field=models.ForeignKey(help_text='Zona !! Base para calculo', on_delete=django.db.models.deletion.PROTECT, to='backend.zona'),
        ),
        migrations.CreateModel(
            name='EstadoCuentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_unidad_tributaria', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto Unidad tributaria', max_digits=14)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cantidad Unidad tributaria', max_digits=14)),
                ('estadocuenta', models.ForeignKey(help_text='ID Cabecera Estado de Cuenta', on_delete=django.db.models.deletion.PROTECT, to='backend.estadocuenta')),
                ('tasamulta', models.ForeignKey(help_text='Id Tasa Multa', on_delete=django.db.models.deletion.PROTECT, to='backend.tasamulta')),
            ],
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='inmueble',
            field=models.ForeignKey(help_text='Sector asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.inmueble'),
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='propietario',
            field=models.ForeignKey(help_text='Sector asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.propietario'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='urbanizacion',
            field=models.ForeignKey(help_text='Urbanizacion asociada', on_delete=django.db.models.deletion.PROTECT, to='backend.urbanizacion'),
        ),
        migrations.AddField(
            model_name='conjuntoresidencial',
            name='urbanizacion',
            field=models.ForeignKey(help_text='Urbanizacion asociada', on_delete=django.db.models.deletion.PROTECT, to='backend.urbanizacion'),
        ),
    ]
