# Generated by Django 4.2 on 2023-05-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_acabadopared_acceso_avenida_calle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExpedienteCatastro', models.PositiveIntegerField(blank=True, help_text='Id de Numero de Expediente de Catastro', null=True)),
            ],
        ),
    ]
