# Generated by Django 4.2 on 2023-05-23 09:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_correlativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Descripcion de la Moneda', unique=True)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Valor de la moneda en Bs.', max_digits=14)),
                ('habilitado', models.BooleanField(default=True, help_text='Esta activo?')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, help_text='Fecha Actualizacion Unidad Tributaria')),
                ('fecha_vigente', models.DateTimeField(blank=True, help_text=' A partir de esta fecha se aplica los calculos')),
                ('monto_unidad_tributaria', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto Unidad tributaria', max_digits=14)),
                ('habilitado', models.BooleanField(default=True, help_text='Esta activo?')),
            ],
        ),
        migrations.RemoveField(
            model_name='estadocuenta',
            name='inmueble',
        ),
        migrations.RemoveField(
            model_name='tasamulta',
            name='monto_unidad_tributaria',
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='total', max_digits=14),
        ),
        migrations.AddField(
            model_name='tasamulta',
            name='aplica',
            field=models.CharField(choices=[('C', 'Catastro'), ('V', 'Vehiculo'), ('P', 'Patente'), ('O', 'Otro')], default='O', help_text='A que tipo de sector aplica', max_length=1),
        ),
        migrations.AddField(
            model_name='tasamulta',
            name='tipo',
            field=models.CharField(choices=[('I', 'Impuesto'), ('T', 'Tasa'), ('M', 'Multa'), ('O', 'Otro')], default='O', help_text='tipo de recaudacion', max_length=1),
        ),
        migrations.CreateModel(
            name='Flujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadocuenta', models.ForeignKey(help_text='ID Cabecera Estado de Cuenta', on_delete=django.db.models.deletion.PROTECT, to='backend.estadocuenta')),
                ('inmueble', models.ForeignKey(help_text='Inmueble', on_delete=django.db.models.deletion.PROTECT, to='backend.inmueble')),
            ],
        ),
    ]
