# Generated by Django 4.2 on 2023-05-23 10:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_moneda_unidadtributaria_remove_estadocuenta_inmueble_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaBCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, help_text='Fecha Actualizacion TASA')),
                ('fecha_vigente', models.DateTimeField(blank=True, help_text=' A partir de esta fecha se aplica los calculos')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto TASA', max_digits=14)),
                ('habilitado', models.BooleanField(default=True, help_text='Esta activo?')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Descripcion Tipo de pago', unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='unidadtributaria',
            old_name='monto_unidad_tributaria',
            new_name='monto',
        ),
        migrations.RemoveField(
            model_name='moneda',
            name='monto',
        ),
        migrations.AddField(
            model_name='correlativo',
            name='NumeroEstadoCuenta',
            field=models.PositiveIntegerField(blank=True, help_text='Numero de Estado de Cuenta', null=True),
        ),
        migrations.AddField(
            model_name='correlativo',
            name='NumeroPago',
            field=models.PositiveIntegerField(blank=True, help_text='Numero de Recibo de pago', null=True),
        ),
        migrations.AddField(
            model_name='estadocuentadetalle',
            name='monto_tasa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto tasa', max_digits=14),
        ),
        migrations.AlterField(
            model_name='correlativo',
            name='ExpedienteCatastro',
            field=models.PositiveIntegerField(blank=True, help_text='Numero de Expediente de Catastro', null=True),
        ),
        migrations.AlterField(
            model_name='estadocuenta',
            name='numero',
            field=models.TextField(help_text='Numero de Estado de Cuenta', unique=True),
        ),
        migrations.CreateModel(
            name='PagoEstadoCuentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto del pago', max_digits=14)),
                ('nro_cuenta', models.TextField(help_text='nro_cuenta')),
                ('fecha', models.TextField(help_text='fecha')),
                ('telefono', models.TextField(help_text='telefono')),
                ('banco', models.TextField(help_text='banco')),
                ('cedula', models.TextField(help_text='cedula')),
                ('estadocuenta', models.ForeignKey(help_text='ID Cabecera Estado de Cuenta', on_delete=django.db.models.deletion.PROTECT, to='backend.estadocuenta')),
                ('tipopago', models.ForeignKey(help_text='Id Tipo Pago', on_delete=django.db.models.deletion.PROTECT, to='backend.tipopago')),
            ],
        ),
        migrations.CreateModel(
            name='PagoEstadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(help_text='Numero de pago', unique=True)),
                ('fecha', models.DateTimeField(blank=True, help_text='Fecha Estado Cuenta')),
                ('observaciones', models.TextField(help_text='observaciones')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='total', max_digits=14)),
                ('estadocuenta', models.ForeignKey(help_text='ID Cabecera Estado de Cuenta', on_delete=django.db.models.deletion.PROTECT, to='backend.estadocuenta')),
                ('propietario', models.ForeignKey(help_text='Contribuyente asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.propietario')),
            ],
        ),
    ]
