# Generated by Django 4.2 on 2023-05-23 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_tasabcv_tipopago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocuenta',
            name='propietario',
            field=models.ForeignKey(help_text='Contribuyente/Propietario asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.propietario'),
        ),
        migrations.AlterField(
            model_name='pagoestadocuenta',
            name='propietario',
            field=models.ForeignKey(help_text='Contribuyente/Propietario asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.propietario'),
        ),
    ]
