# Generated by Django 4.2 on 2023-05-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_modulo_perfil_permiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasabcv',
            name='fecha',
            field=models.DateField(blank=True, help_text='Fecha Actualizacion TASA'),
        ),
        migrations.AlterField(
            model_name='tasabcv',
            name='fecha_vigente',
            field=models.DateField(blank=True, help_text=' A partir de esta fecha se aplica los calculos'),
        ),
        migrations.AlterField(
            model_name='unidadtributaria',
            name='fecha',
            field=models.DateField(blank=True, help_text='Fecha Actualizacion Unidad Tributaria'),
        ),
        migrations.AlterField(
            model_name='unidadtributaria',
            name='fecha_vigente',
            field=models.DateField(blank=True, help_text=' A partir de esta fecha se aplica los calculos'),
        ),
    ]
