# Generated by Django 4.2 on 2023-05-25 15:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_inmueble_fecha_inscripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadocuenta',
            old_name='monto',
            new_name='monto_total',
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='valor_petro',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='total', max_digits=14),
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='valor_tasa_bs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='total', max_digits=14),
        ),
        migrations.AlterField(
            model_name='estadocuentadetalle',
            name='monto_tasa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto total del renglon tasa(monto_unidad_tributaria * cantidad)', max_digits=14),
        ),
    ]
