# Generated by Django 4.2 on 2023-05-25 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_monto_estadocuenta_monto_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='ambito',
            field=models.ForeignKey(blank=True, help_text='ambito asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ambito'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='avenida',
            field=models.ForeignKey(blank=True, help_text='avenida asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.avenida'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='calle',
            field=models.ForeignKey(blank=True, help_text='calle asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.calle'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='conjunto_residencial',
            field=models.ForeignKey(blank=True, help_text='Sector asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.conjuntoresidencial'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='direccion',
            field=models.TextField(blank=True, help_text='direccion', null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='edificio',
            field=models.ForeignKey(blank=True, help_text='edificio asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.edificio'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='manzana',
            field=models.ForeignKey(blank=True, help_text='manzana asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.manzana'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='nivel',
            field=models.ForeignKey(blank=True, help_text='nivel asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.nivelinmueble'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='numero_casa',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='numero_civico',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='numero_piso',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='observaciones',
            field=models.TextField(blank=True, help_text='observaciones', null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='parcela',
            field=models.ForeignKey(blank=True, help_text='parcela asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.parcela'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='referencia',
            field=models.TextField(blank=True, help_text='referencia', null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Sector asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.sector'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='status',
            field=models.ForeignKey(blank=True, help_text='status asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.estatusinmueble'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='subparcela',
            field=models.ForeignKey(blank=True, help_text='subparcela asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.subparcela'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='telefono',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='TipoInmueble asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipoinmueble'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='torre',
            field=models.ForeignKey(blank=True, help_text='Sector asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.torre'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='unidad',
            field=models.ForeignKey(blank=True, help_text='unidad asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.unidadinmueble'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='urbanizacion',
            field=models.ForeignKey(blank=True, help_text='urbanizacion', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.urbanizacion'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='zona',
            field=models.ForeignKey(blank=True, help_text='Zona !! Base para calculo', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.zona'),
        ),
        migrations.AlterField(
            model_name='inmuebleconstruccion',
            name='observaciones',
            field=models.TextField(blank=True, help_text='observaciones', null=True),
        ),
    ]
