# Generated by Django 4.2 on 2023-05-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_inmueble_ambito_alter_inmueble_avenida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='menu',
            field=models.TextField(blank=True, help_text='nombre del menu, si el mudulo es enu este campo esta vacio', null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='titulo',
            field=models.TextField(blank=True, help_text='Titulo de la opcion/menu', null=True),
        ),
    ]
