# Generated by Django 4.2 on 2023-05-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_modulo_menu_modulo_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='es_menu',
            field=models.BooleanField(default=False, help_text='es un menu?'),
        ),
    ]
