# Generated by Django 4.2 on 2023-05-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_modulo_es_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='orden',
            field=models.PositiveIntegerField(blank=True, help_text='Orden del menu y de la opcion dentro de menu', null=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='menu',
            field=models.TextField(blank=True, help_text='nombre del menu, si el modulo es menu este campo esta vacio', null=True),
        ),
    ]
