# Generated by Django 4.2 on 2023-05-30 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_modulo_orden_alter_modulo_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['menu', 'es_menu']},
        ),
    ]
