# Generated by Django 4.2 on 2023-06-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_modulo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='icono',
            field=models.TextField(blank=True, help_text='Icono a mostrar', null=True),
        ),
    ]
