# Generated by Django 4.2 on 2023-06-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_modulo_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlativo',
            name='NumeroLiquidacion',
            field=models.PositiveIntegerField(blank=True, help_text='Numero de NumeroLiquidacion', null=True),
        ),
    ]
