# Generated by Django 4.2 on 2023-06-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_correlativo_numeroliquidacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlativo',
            name='NumeroPago',
            field=models.PositiveIntegerField(blank=True, help_text='Numero de Recibo de pagos', null=True),
        ),
    ]
