# Generated by Django 4.2 on 2023-06-05 13:22

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_correlativo_numeropago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(help_text='Numero de Liquidacion', unique=True)),
                ('fecha', models.DateTimeField(blank=True, help_text='Fecha Estado Cuenta')),
                ('observaciones', models.TextField(help_text='observaciones')),
                ('valor_petro', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='total', max_digits=14)),
                ('valor_tasa_bs', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='total', max_digits=14)),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='total', max_digits=14)),
                ('estadocuenta', models.ForeignKey(help_text='ID Cabecera Estado de Cuenta', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.estadocuenta')),
                ('propietario', models.ForeignKey(help_text='Contribuyente/Propietario asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_unidad_tributaria', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto Unidad tributaria', max_digits=14)),
                ('monto_tasa', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto total del renglon tasa(monto_unidad_tributaria * cantidad)', max_digits=14)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cantidad Unidad tributaria', max_digits=14)),
                ('liquidacion', models.ForeignKey(help_text='ID Cabecera liquidacion', on_delete=django.db.models.deletion.PROTECT, to='backend.liquidacion')),
                ('tasamulta', models.ForeignKey(help_text='Id Tasa Multa', on_delete=django.db.models.deletion.PROTECT, to='backend.tasamulta')),
            ],
        ),
    ]
