# Generated by Django 4.2 on 2023-06-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_liquidacion_liquidaciondetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasamulta',
            name='aplica',
            field=models.CharField(choices=[('C', 'Catastro'), ('V', 'Vehiculo'), ('P', 'Patente'), ('I', 'Industria y Comercio'), ('O', 'Otro')], default='O', help_text='A que tipo de sector aplica', max_length=1),
        ),
    ]
