# Generated by Django 4.2 on 2023-06-05 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_tasamulta_aplica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoestadocuentadetalle',
            name='estadocuenta',
        ),
        migrations.RemoveField(
            model_name='pagoestadocuentadetalle',
            name='tipopago',
        ),
        migrations.RemoveField(
            model_name='flujo',
            name='estadocuenta',
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='estadocuenta',
            field=models.ForeignKey(blank=True, help_text='ID Cabecera Estado de Cuenta', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.estadocuenta'),
        ),
        migrations.DeleteModel(
            name='PagoEstadoCuenta',
        ),
        migrations.DeleteModel(
            name='PagoEstadoCuentaDetalle',
        ),
    ]
