# Generated by Django 4.2 on 2023-06-05 16:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_remove_pagoestadocuentadetalle_estadocuenta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoEstadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(help_text='Numero de pago', unique=True)),
                ('fecha', models.DateTimeField(blank=True, help_text='Fecha Estado Cuenta')),
                ('observaciones', models.TextField(help_text='observaciones')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='total', max_digits=14)),
            ],
        ),
    ]
