# Generated by Django 4.2 on 2023-06-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_pagoestadocuenta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PagoEstadoCuenta',
        ),
    ]
