# Generated by Django 4.2 on 2023-06-05 16:43

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_delete_pagoestadocuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoEstadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(help_text='Numero de pago', unique=True)),
                ('fecha', models.DateTimeField(blank=True, help_text='Fecha Estado Cuenta')),
                ('observaciones', models.TextField(help_text='observaciones')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='total', max_digits=14)),
                ('liquidacion', models.ForeignKey(help_text='ID Cabecera liquidacion', on_delete=django.db.models.deletion.PROTECT, to='backend.liquidacion')),
            ],
        ),
    ]
