# Generated by Django 4.2 on 2023-06-05 16:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_pagoestadocuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoEstadoCuentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto del pago', max_digits=14)),
                ('nro_cuenta', models.TextField(help_text='nro_cuenta')),
                ('fecha', models.TextField(help_text='fecha')),
                ('telefono', models.TextField(help_text='telefono')),
                ('banco', models.TextField(help_text='banco')),
                ('cedula', models.TextField(help_text='cedula')),
                ('pagoestadocuenta', models.ForeignKey(help_text='ID Cabecera Estado de Cuenta', on_delete=django.db.models.deletion.PROTECT, to='backend.pagoestadocuenta')),
                ('tipopago', models.ForeignKey(help_text='Id Tipo Pago', on_delete=django.db.models.deletion.PROTECT, to='backend.tipopago')),
            ],
        ),
    ]
