# Generated by Django 4.2 on 2023-06-05 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_pagoestadocuentadetalle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flujo',
        ),
    ]
