# Generated by Django 4.2 on 2023-06-06 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_pagoestadocuentadetalle_pagoestadocuenta_flujo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('nombre', models.CharField(help_text='Nombre Depatamento para usuario de catastro FLUJO', max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FujoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'Pendiente por Recibir'), ('2', 'Recibido'), ('3', 'Pendiente por Procesar'), ('4', 'Procesado'), ('5', 'Pendiente por Enviar'), ('6', 'Enviado'), ('7', 'Finalizado'), ('8', 'Fin del Proceso')], default='1', help_text='Estado del proceso', max_length=1)),
                ('flujo', models.ForeignKey(help_text='ID Cabecera PAGO', on_delete=django.db.models.deletion.PROTECT, to='backend.flujo')),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='departamento',
            field=models.ForeignKey(blank=True, help_text='Departamento del usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.departamento'),
        ),
    ]
