# Generated by Django 4.2 on 2023-06-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_departamento_fujodetalle_perfil_departamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FujoDetalle',
        ),
    ]
