# Generated by Django 4.2 on 2023-06-06 10:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0031_fujodetalle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FujoDetalle',
            new_name='FlujoDetalle',
        ),
    ]
