# Generated by Django 4.2 on 2023-06-06 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_alter_flujodetalle_envia_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujodetalle',
            name='procesa_fecha',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Fecha procesado'),
            preserve_default=False,
        ),
    ]
