# Generated by Django 4.2 on 2023-06-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_flujodetalle_procesa_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujodetalle',
            name='envia_fecha',
            field=models.DateTimeField(blank=True, help_text='Fecha enviado', null=True),
        ),
        migrations.AlterField(
            model_name='flujodetalle',
            name='procesa_fecha',
            field=models.DateTimeField(blank=True, help_text='Fecha procesado', null=True),
        ),
        migrations.AlterField(
            model_name='flujodetalle',
            name='recibe_fecha',
            field=models.DateTimeField(blank=True, help_text='Fecha recepcion', null=True),
        ),
    ]
