# Generated by Django 4.2 on 2023-06-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_alter_flujodetalle_envia_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujo',
            name='fecha',
            field=models.DateTimeField(blank=True, help_text='Fecha creacion', null=True),
        ),
    ]
