# Generated by Django 4.2 on 2023-06-06 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_flujo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='modulo',
            field=models.ForeignKey(blank=True, help_text='Modulo INICAL al entrar', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.modulo'),
        ),
    ]
