# Generated by Django 4.2 on 2023-06-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_perfil_modulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujodetalle',
            name='fin_fecha',
            field=models.DateTimeField(blank=True, help_text='Fecha FIN DE PROCESO', null=True),
        ),
        migrations.AddField(
            model_name='flujodetalle',
            name='inicio_proceso_fecha',
            field=models.DateTimeField(blank=True, help_text='Fecha Inicio de proceso', null=True),
        ),
        migrations.AlterField(
            model_name='flujodetalle',
            name='estado',
            field=models.CharField(choices=[('1', 'Pendiente por Recibir'), ('2', 'Recibido'), ('3', 'Pendiente por Procesar'), ('4', 'En proceso'), ('5', 'Procesado'), ('6', 'Pendiente por Enviar'), ('7', 'Enviado'), ('8', 'Finalizado'), ('9', 'Fin del Proceso')], default='1', help_text='Estado del proceso', max_length=1),
        ),
        migrations.AlterField(
            model_name='flujodetalle',
            name='procesa_fecha',
            field=models.DateTimeField(blank=True, help_text='Fecha FIN de proceso', null=True),
        ),
        migrations.AlterField(
            model_name='flujodetalle',
            name='tarea',
            field=models.CharField(choices=[('1', 'Pendiente por Recibir'), ('3', 'Pendiente por Procesar'), ('6', 'Pendiente por Enviar')], default='1', help_text='Estado del proceso', max_length=1),
        ),
    ]
