# Generated by Django 4.2 on 2023-06-07 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_flujodetalle_fin_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFlujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Descripcion Tipo de pago', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='tipoflujo',
            field=models.ForeignKey(blank=True, help_text='Tipo de flujo (solo catasrro: inscripcion, actualizacion o modificar propietario', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipoflujo'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='tipoflujo',
            field=models.ForeignKey(blank=True, help_text='Tipo de flujo (solo catasrro: inscripcion, actualizacion o modificar propietario', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipoflujo'),
        ),
    ]
