# Generated by Django 4.2 on 2023-06-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_alter_liquidacion_tipoflujo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidacion',
            name='tipoflujo',
        ),
    ]
