# Generated by Django 4.2 on 2023-06-07 13:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_liquidacion_tipoflujo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocuenta',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='monto total', max_digits=14),
        ),
    ]
