# Generated by Django 4.2 on 2023-06-08 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_alter_estadocuenta_monto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocuenta',
            name='inmueble',
            field=models.ForeignKey(blank=True, help_text='Id Inmueble asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.inmueble'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='inmueble',
            field=models.ForeignKey(blank=True, help_text='Id Inmueble asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.inmueble'),
        ),
    ]
