# Generated by Django 4.2 on 2023-06-08 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_estadocuenta_inmueble_liquidacion_inmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujodetalle',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='usuario asociado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FujoDetalle_recibe_usuario', to='backend.perfil'),
        ),
    ]
