# Generated by Django 4.2 on 2023-06-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_flujodetalle_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flujodetalle',
            name='usuario',
        ),
        migrations.AddField(
            model_name='flujodetalle',
            name='usuario_envia',
            field=models.ForeignKey(blank=True, help_text='usuario envia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FlujoDetalle_usuario_envia', to='backend.perfil'),
        ),
        migrations.AddField(
            model_name='flujodetalle',
            name='usuario_recibe',
            field=models.ForeignKey(blank=True, help_text='usuario recibe', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FlujoDetalle_usuario_recibe', to='backend.perfil'),
        ),
    ]
