# Generated by Django 4.2 on 2023-06-09 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_remove_flujodetalle_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujodetalle',
            name='departamento_envia',
            field=models.ForeignKey(blank=True, help_text='Departamento envia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FlujoDetalle_departamento_envia', to='backend.departamento'),
        ),
        migrations.AddField(
            model_name='flujodetalle',
            name='departamento_recibe',
            field=models.ForeignKey(blank=True, help_text='Departamento recibe', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FlujoDetalle_departamento_recibe', to='backend.departamento'),
        ),
        migrations.AlterField(
            model_name='flujodetalle',
            name='estado',
            field=models.CharField(choices=[('1', 'Pendiente por Recibir'), ('2', 'Recibido'), ('3', 'Pendiente por Procesar'), ('4', 'En proceso'), ('5', 'Proceso Culminado'), ('6', 'Pendiente por Enviar'), ('7', 'Enviado'), ('8', 'Finalizado'), ('9', 'Fin del Proceso')], default='1', help_text='Estado del proceso', max_length=1),
        ),
    ]
