# Generated by Django 4.2 on 2023-06-10 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0050_remove_flujodetalle_usuario_envia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujodetalle',
            name='recibe_usuario',
            field=models.ForeignKey(blank=True, help_text='usuario asociado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FujoDetalle_recibe_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
