# Generated by Django 4.2 on 2023-06-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_alter_flujodetalle_recibe_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujo',
            name='estado',
            field=models.CharField(choices=[('1', 'En Proceso'), ('2', 'Cerrado')], default='1', help_text='Estado dela solicitud', max_length=1),
        ),
        migrations.AlterField(
            model_name='flujodetalle',
            name='estado',
            field=models.CharField(choices=[('1', 'Pendiente por Recibir'), ('2', 'Recibido'), ('3', 'Pendiente por Procesar'), ('4', 'En proceso'), ('5', 'Proceso Culminado'), ('6', 'Pendiente por Enviar'), ('7', 'Enviado'), ('8', 'Finalizado'), ('9', 'Fin de la Solicitud'), ('0', 'Pendiente por Re-Enviar')], default='1', help_text='Estado del proceso', max_length=1),
        ),
        migrations.AlterField(
            model_name='flujodetalle',
            name='tarea',
            field=models.CharField(choices=[('1', 'Pendiente por Recibir'), ('3', 'Pendiente por Procesar'), ('6', 'Pendiente por Enviar'), ('7', 'Devuelto'), ('8', 'Finalizado')], default='1', help_text='Estado del proceso', max_length=1),
        ),
    ]
