# Generated by Django 4.2 on 2023-06-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_flujo_estado_alter_flujodetalle_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocuenta',
            name='habilitado',
            field=models.BooleanField(default=True, help_text='Esta activo?'),
        ),
    ]
