# Generated by Django 4.2 on 2023-06-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_liquidacion_habilitado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='habilitado',
            field=models.BooleanField(default=True, help_text='Se muestra la liquidacion?'),
        ),
    ]
