# Generated by Django 4.2 on 2023-06-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_alter_liquidacion_habilitado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoestadocuentadetalle',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='pagoestadocuentadetalle',
            name='nro_cuenta',
        ),
    ]
