# Generated by Django 4.2 on 2023-06-13 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_banco_bancocuenta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoestadocuentadetalle',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='pagoestadocuentadetalle',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='pagoestadocuentadetalle',
            name='tipopago',
        ),
        migrations.AddField(
            model_name='pagoestadocuentadetalle',
            name='bancocuenta',
            field=models.ForeignKey(default=1, help_text='ID Banco', on_delete=django.db.models.deletion.PROTECT, to='backend.bancocuenta'),
            preserve_default=False,
        ),
    ]
