# Generated by Django 4.2 on 2023-06-13 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_remove_pagoestadocuentadetalle_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoestadocuentadetalle',
            name='tipopago',
            field=models.ForeignKey(default=1, help_text='Id Tipo Pago', on_delete=django.db.models.deletion.PROTECT, to='backend.tipopago'),
            preserve_default=False,
        ),
    ]
