# Generated by Django 4.2 on 2023-06-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_remove_pagoestadocuentadetalle_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoestadocuentadetalle',
            name='fecha',
            field=models.TextField(blank=True, help_text='fecha', null=True),
        ),
    ]
