# Generated by Django 4.2 on 2023-06-13 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_remove_pagoestadocuentadetalle_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoestadocuentadetalle',
            name='bancocuenta',
            field=models.ForeignKey(blank=True, help_text='ID Banco', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.bancocuenta'),
        ),
    ]
