# Generated by Django 4.2 on 2023-06-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0064_alter_pagoestadocuentadetalle_bancocuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='fecha_inscripcion',
            field=models.DateField(blank=True, help_text='fecha de inscripcion', null=True),
        ),
    ]
