# Generated by Django 4.2 on 2023-06-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0065_alter_inmueble_fecha_inscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueblefaltante',
            name='doumento_propiedad',
        ),
        migrations.AddField(
            model_name='inmueblefaltante',
            name='documentopropiedad',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='estadocuenta',
            name='observaciones',
            field=models.TextField(blank=True, help_text='observaciones', null=True),
        ),
        migrations.AlterField(
            model_name='flujodetalle',
            name='observaciones',
            field=models.TextField(blank=True, help_text='observaciones', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleconstruccion',
            name='edad_efectiva',
            field=models.TextField(blank=True, help_text='edad_efectiva', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleconstruccion',
            name='porcentaje_refaccion',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblefaltante',
            name='cedula',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblefaltante',
            name='observaciones',
            field=models.TextField(blank=True, help_text='observaciones', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='anio_folio_documento',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='folio_construccion',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='folio_terreno',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='lindero_este',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='lindero_norte',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='lindero_oeste',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='lindero_sur',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='matricula_documento',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='numero_construccion',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='numero_terreno',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='protocolo_construccion',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='protocolo_terreno',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='tomo_construccion',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='tomo_terreno',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='valor_terreno',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleterreno',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='g1_este',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='g1_norte',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='g2_este',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='g2_norte',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='g3_este',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='g3_norte',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='g4_este',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='g4_norte',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='g5_este',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='g5_norte',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='g6_este',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='g6_norte',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='g7_este',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='g7_norte',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='g8_este',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='g8_norte',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='lindero_este',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='lindero_norte',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='lindero_oeste',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='lindero_sur',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblevaloracionconstruccion',
            name='observaciones',
            field=models.TextField(blank=True, help_text='observaciones', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblevaloracionterreno',
            name='observaciones',
            field=models.TextField(blank=True, help_text='observaciones', null=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='observaciones',
            field=models.TextField(blank=True, help_text='observaciones', null=True),
        ),
        migrations.AlterField(
            model_name='manzana',
            name='perimetro',
            field=models.TextField(blank=True, help_text='Perimetro de la manzana', null=True),
        ),
        migrations.AlterField(
            model_name='pagoestadocuenta',
            name='observaciones',
            field=models.TextField(blank=True, help_text='observaciones', null=True),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='perimetro',
            field=models.TextField(blank=True, help_text='Perimetro de la Parcela', null=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='emaill_secundario',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefono_secundario',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='perimetro',
            field=models.TextField(blank=True, help_text='Descripcion del Sector', null=True),
        ),
        migrations.AlterField(
            model_name='subparcela',
            name='perimetro',
            field=models.TextField(blank=True, help_text='Perimetro de la SubParcela', null=True),
        ),
    ]
