# Generated by Django 4.2 on 2023-06-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0066_remove_inmueblefaltante_doumento_propiedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlativo',
            name='NumeroSolicitud',
            field=models.PositiveIntegerField(blank=True, help_text='Numero de Solicitud', null=True),
        ),
        migrations.AddField(
            model_name='flujo',
            name='numero',
            field=models.TextField(default=1, help_text='Numero de Solicitud', unique=True),
            preserve_default=False,
        ),
    ]
