# Generated by Django 4.2 on 2023-06-15 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0067_correlativo_numerosolicitud_flujo_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoflujo',
            name='vencimiento',
            field=models.PositiveIntegerField(blank=True, help_text='dias vencimiento pra validar el estado de cuenta', null=True),
        ),
        migrations.CreateModel(
            name='TipoFlujoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasamulta', models.ForeignKey(help_text='Id Tasa Multa', on_delete=django.db.models.deletion.PROTECT, to='backend.tasamulta')),
                ('tipoflujo', models.ForeignKey(blank=True, help_text='Id TipoFlujo', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipoflujo')),
            ],
        ),
    ]
