# Generated by Django 4.2 on 2023-06-22 09:16

import backend.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_tipoflujo_vencimiento_tipoflujodetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmuebleconstruccion',
            name='acabado_pared',
            field=models.ForeignKey(blank=True, help_text='AcabadoPared asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.acabadopared'),
        ),
        migrations.AlterField(
            model_name='inmuebleconstruccion',
            name='conservacion',
            field=models.ForeignKey(blank=True, help_text='Conservacion asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.conservacion'),
        ),
        migrations.AlterField(
            model_name='inmuebleconstruccion',
            name='regimen',
            field=models.ForeignKey(blank=True, help_text='regimen asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.regimen'),
        ),
        migrations.AlterField(
            model_name='inmuebleconstruccion',
            name='tenencia',
            field=models.ForeignKey(blank=True, help_text='tenencia asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipotenencia'),
        ),
        migrations.AlterField(
            model_name='inmuebleconstruccion',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='TipoInmueble asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipoinmueble'),
        ),
        migrations.AlterField(
            model_name='inmuebleconstruccion',
            name='tipo_pared',
            field=models.ForeignKey(blank=True, help_text='TipoPared asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipopared'),
        ),
        migrations.AlterField(
            model_name='inmuebleconstruccion',
            name='uso_construccion',
            field=models.ForeignKey(blank=True, help_text='uso_construccion asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.usoconstruccion'),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='area_construccion',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='area_construccion en m2', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='area_terreno',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='area_terreno en m2', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='fecha_construccion',
            field=models.DateField(blank=True, help_text='fecha de inscripcion', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='fecha_documento',
            field=models.DateField(blank=True, help_text='fecha de inscripcion', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='fecha_habitabilidad',
            field=models.DateField(blank=True, help_text='fecha_habitabilidad', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='fecha_vigencia',
            field=models.DateField(blank=True, help_text='fecha de inscripcion', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='numero_documento',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, help_text='Sector asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipodocumento'),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='tipo_especial',
            field=models.ForeignKey(blank=True, help_text='Sector asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipoespecial'),
        ),
        migrations.AlterField(
            model_name='inmuebleterreno',
            name='forma',
            field=models.ForeignKey(blank=True, help_text='Forma asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.forma'),
        ),
        migrations.AlterField(
            model_name='inmuebleterreno',
            name='servicios',
            field=models.ForeignKey(blank=True, help_text='Servicios Asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.servicios'),
        ),
        migrations.AlterField(
            model_name='inmuebleterreno',
            name='tenencia',
            field=models.ForeignKey(blank=True, help_text='tenencia asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipotenencia'),
        ),
        migrations.AlterField(
            model_name='inmuebleterreno',
            name='ubicacion',
            field=models.ForeignKey(blank=True, help_text='Ubicacion asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ubicacion'),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='imagan_plano_mesura',
            field=models.ImageField(blank=True, help_text='Imagen asociado al pais', null=True, upload_to=backend.models.immuebles_path),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='imagen_inmueble',
            field=models.ImageField(blank=True, help_text='Imagen asociado al pais', null=True, upload_to=backend.models.immuebles_path),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='imagen_plano',
            field=models.ImageField(blank=True, help_text='Imagen asociado al pais', null=True, upload_to=backend.models.immuebles_path),
        ),
        migrations.AlterField(
            model_name='inmueblevaloracionterreno',
            name='fines_fiscales',
            field=models.ForeignKey(blank=True, help_text='fines_fiscales asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.finesfiscales'),
        ),
        migrations.AlterField(
            model_name='inmueblevaloracionterreno',
            name='forma_factor_ajuste',
            field=models.ForeignKey(blank=True, help_text='Forma del factor de ajuste', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.forma'),
        ),
        migrations.AlterField(
            model_name='inmueblevaloracionterreno',
            name='tipologia',
            field=models.ForeignKey(blank=True, help_text='tipologia asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipologia'),
        ),
    ]
