# Generated by Django 4.2 on 2023-06-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_alter_inmuebleconstruccion_acabado_pared_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueblefaltante',
            name='cedula',
            field=models.TextField(blank=True, help_text='Numero de cedula', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblefaltante',
            name='documentopropiedad',
            field=models.TextField(blank=True, help_text='Numero de documentopropiedad', null=True),
        ),
        migrations.AlterField(
            model_name='tipodesincorporacion',
            name='descripcion',
            field=models.TextField(help_text='descripcion del tipo de desincorporacion (cuando se desincorpora un propietario de un inmueble)', unique=True),
        ),
    ]
