# Generated by Django 4.2 on 2023-06-30 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0070_alter_inmueblefaltante_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='fecha_terreno',
            field=models.DateField(blank=True, help_text='fecha de inscripcion', null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='tipo_tenencia',
            field=models.ForeignKey(blank=True, help_text='tipo_tenencia asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipotenencia'),
        ),
    ]
