# Generated by Django 4.2 on 2023-07-03 09:23

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0071_alter_inmueblepropiedad_fecha_terreno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipologia',
            name='habilitado',
            field=models.BooleanField(default=True, help_text='Esta activo?'),
        ),
        migrations.AddField(
            model_name='tipologia',
            name='m2desde',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Area en m2', max_digits=14),
        ),
        migrations.AddField(
            model_name='tipologia',
            name='m2hasta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Area en m2', max_digits=14),
        ),
        migrations.AddField(
            model_name='tipologia',
            name='se_lista',
            field=models.BooleanField(default=True, help_text='Se muestra en las listas'),
        ),
        migrations.AddField(
            model_name='tipologia',
            name='tarifa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Tarifa o Alicuota', max_digits=14),
        ),
        migrations.AddField(
            model_name='tipologia',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Valor', max_digits=14),
        ),
        migrations.AddField(
            model_name='tipologia',
            name='zona',
            field=models.ForeignKey(blank=True, help_text='Zona !! Base para calculo', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.zona'),
        ),
    ]
