# Generated by Django 4.2 on 2023-07-03 16:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0072_tipologia_habilitado_tipologia_m2desde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueblevaloracionconstruccion',
            name='valor_actual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='valor', max_digits=14),
        ),
    ]
