# Generated by Django 4.2 on 2023-07-04 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0073_inmueblevaloracionconstruccion_valor_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueblevaloracionconstruccion',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='inmueblevaloracionconstruccion',
            name='fecha_compra',
        ),
        migrations.RemoveField(
            model_name='inmueblevaloracionconstruccion',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='inmueblevaloracionconstruccion',
            name='trimestre',
        ),
        migrations.AddField(
            model_name='inmueblevaloracionconstruccion',
            name='fecha_construccion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='fecha construccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueblevaloracionconstruccion',
            name='sub_utilizado',
            field=models.BooleanField(default=True, help_text='subutilizado si o no'),
        ),
    ]
