# Generated by Django 4.2 on 2023-07-05 09:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0074_remove_inmueblevaloracionconstruccion_anio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocuenta',
            name='monto_total',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='monto total', max_digits=22),
        ),
        migrations.AlterField(
            model_name='estadocuenta',
            name='valor_petro',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='total', max_digits=22),
        ),
        migrations.AlterField(
            model_name='estadocuenta',
            name='valor_tasa_bs',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='total', max_digits=22),
        ),
        migrations.AlterField(
            model_name='estadocuentadetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Cantidad Unidad tributaria', max_digits=22),
        ),
        migrations.AlterField(
            model_name='estadocuentadetalle',
            name='monto_tasa',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Monto total del renglon tasa(monto_unidad_tributaria * cantidad)', max_digits=22),
        ),
        migrations.AlterField(
            model_name='estadocuentadetalle',
            name='monto_unidad_tributaria',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Monto Unidad tributaria', max_digits=22),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='area_construccion',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='area_construccion en m2', max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='area_terreno',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='area_terreno en m2', max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='inmueblevaloracionconstruccion',
            name='area',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Area en m2', max_digits=22),
        ),
        migrations.AlterField(
            model_name='inmueblevaloracionconstruccion',
            name='depreciacion',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='depreciacion', max_digits=22),
        ),
        migrations.AlterField(
            model_name='inmueblevaloracionconstruccion',
            name='valor',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='valor', max_digits=22),
        ),
        migrations.AlterField(
            model_name='inmueblevaloracionconstruccion',
            name='valor_actual',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='valor', max_digits=22),
        ),
        migrations.AlterField(
            model_name='inmueblevaloracionterreno',
            name='area',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Area en m2', max_digits=22),
        ),
        migrations.AlterField(
            model_name='inmueblevaloracionterreno',
            name='area_factor_ajuste',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Area en m2 del factor de ajuste', max_digits=22),
        ),
        migrations.AlterField(
            model_name='inmueblevaloracionterreno',
            name='valor_ajustado',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Valor Ajustado', max_digits=22),
        ),
        migrations.AlterField(
            model_name='inmueblevaloracionterreno',
            name='valor_total',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Valor Total', max_digits=22),
        ),
        migrations.AlterField(
            model_name='inmueblevaloracionterreno',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='valor_unitario', max_digits=22),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='monto_total',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='total', max_digits=22),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='valor_petro',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='total', max_digits=22),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='valor_tasa_bs',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='total', max_digits=22),
        ),
        migrations.AlterField(
            model_name='liquidaciondetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Cantidad Unidad tributaria', max_digits=22),
        ),
        migrations.AlterField(
            model_name='liquidaciondetalle',
            name='monto_tasa',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Monto total del renglon tasa(monto_unidad_tributaria * cantidad)', max_digits=22),
        ),
        migrations.AlterField(
            model_name='liquidaciondetalle',
            name='monto_unidad_tributaria',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Monto Unidad tributaria', max_digits=22),
        ),
        migrations.AlterField(
            model_name='manzana',
            name='area',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Area en m2', max_digits=22),
        ),
        migrations.AlterField(
            model_name='pagoestadocuenta',
            name='monto',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='total', max_digits=22),
        ),
        migrations.AlterField(
            model_name='pagoestadocuentadetalle',
            name='monto',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Monto del pago', max_digits=22),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='area',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Area en m2', max_digits=22),
        ),
        migrations.AlterField(
            model_name='sector',
            name='area',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Area en m2', max_digits=22),
        ),
        migrations.AlterField(
            model_name='subparcela',
            name='area',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Area en m2', max_digits=22),
        ),
        migrations.AlterField(
            model_name='tasabcv',
            name='monto',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Monto TASA', max_digits=22),
        ),
        migrations.AlterField(
            model_name='tipologia',
            name='m2desde',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Area en m2', max_digits=22),
        ),
        migrations.AlterField(
            model_name='tipologia',
            name='m2hasta',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Area en m2', max_digits=22),
        ),
        migrations.AlterField(
            model_name='tipologia',
            name='tarifa',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Tarifa o Alicuota', max_digits=22),
        ),
        migrations.AlterField(
            model_name='tipologia',
            name='valor',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Valor', max_digits=22),
        ),
        migrations.AlterField(
            model_name='unidadtributaria',
            name='monto',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Monto Unidad tributaria', max_digits=22),
        ),
    ]
