# Generated by Django 4.2 on 2023-07-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0075_alter_estadocuenta_monto_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipologia',
            name='observaciones',
            field=models.TextField(blank=True, help_text='observaciones en caso de no esar hablita por que cambio el valor a causa de una ordenanza nueva.', null=True),
        ),
    ]
