# Generated by Django 4.2 on 2023-07-18 20:16

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0076_tipologia_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmuebleterreno',
            name='servicios',
        ),
        migrations.AddField(
            model_name='inmueblevaloracionconstruccion',
            name='tipo',
            field=models.CharField(choices=[('U', 'Unifamiliar'), ('M', 'Multifamiliar'), ('X', 'No Aplica')], default='X', help_text='Para cálculo de multas', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='imagan_plano_mesura',
            field=models.ImageField(blank=True, help_text='Imagen asociado al Plano Mesura', null=True, upload_to=backend.models.immuebles_path),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='imagen_inmueble',
            field=models.ImageField(blank=True, help_text='Imagen asociado al Inmueble', null=True, upload_to=backend.models.immuebles_path),
        ),
        migrations.AlterField(
            model_name='inmuebleubicacion',
            name='imagen_plano',
            field=models.ImageField(blank=True, help_text='Imagen asociado al Plano', null=True, upload_to=backend.models.immuebles_path),
        ),
        migrations.CreateModel(
            name='InmuebleTerrenoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmueble_terreno', models.ForeignKey(help_text='Inmueble asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.inmuebleterreno')),
                ('servicio', models.ForeignKey(help_text='regimen asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.servicios')),
            ],
        ),
    ]
