# Generated by Django 4.2 on 2023-07-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0077_remove_inmuebleterreno_servicios_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueblevaloracionconstruccion',
            old_name='inmueble_terreno',
            new_name='inmueblevaloracionterreno',
        ),
    ]
