# Generated by Django 4.2 on 2023-07-19 15:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0079_inmuebleterreno_regimen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocuenta',
            name='area',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Area en m2 (SOLO SE PIDE PARA INSCRIPCION DE INMUEBLES NUEVOS)', max_digits=22),
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='fecha_compra',
            field=models.DateField(blank=True, help_text='Fecha de compra del inmueble (SOLO SE PIDE PARA INSCRIPCION DE INMUEBLES NUEVOS)', null=True),
        ),
        migrations.AddField(
            model_name='estadocuenta',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='TipoInmueble asociado (SOLO SE PIDE PARA INSCRIPCION DE INMUEBLES NUEVOS)', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipoinmueble'),
        ),
        migrations.AddField(
            model_name='inmueblepropietarios',
            name='fecha_compra',
            field=models.DateField(blank=True, help_text='fecha de compra del inmueble', null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='area',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Area en m2 (SOLO SE PIDE PARA INSCRIPCION DE INMUEBLES NUEVOS)', max_digits=22),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='fecha_compra',
            field=models.DateField(blank=True, help_text='Fecha de compra del inmueble (SOLO SE PIDE PARA INSCRIPCION DE INMUEBLES NUEVOS)', null=True),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='TipoInmueble asociado (SOLO SE PIDE PARA INSCRIPCION DE INMUEBLES NUEVOS)', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipoinmueble'),
        ),
        migrations.AddField(
            model_name='tipoinmueble',
            name='tipo',
            field=models.CharField(choices=[('U', 'Unifamiliar Residencial'), ('M', 'Multifamiliar No residencial')], default='U', help_text='Requerido para cálculo de multas artículo 99 y 101', max_length=1, null=True),
        ),
    ]
