# Generated by Django 4.2 on 2023-07-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0080_estadocuenta_area_estadocuenta_fecha_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasamulta',
            name='detalle',
            field=models.TextField(blank=True, help_text='Información extra. en caso de un artoculo especifico de la ordenanza', null=True, unique=True),
        ),
    ]
