# Generated by Django 4.2 on 2023-07-19 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0081_tasamulta_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueblevaloracionconstruccion',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Tipo de Inmueble asociado para determinar si unifamiliar o multifamiliar', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipoinmueble'),
        ),
    ]
