# Generated by Django 4.2 on 2023-07-19 20:45

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0082_alter_inmueblevaloracionconstruccion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueblepropiedad',
            name='pdf_documento',
            field=models.FileField(blank=True, help_text='Pdf del documento de registro', null=True, upload_to=backend.models.immuebles_path),
        ),
    ]
