# Generated by Django 4.2 on 2023-07-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0083_inmueblepropiedad_pdf_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoflujo',
            name='codigo',
            field=models.TextField(blank=True, help_text='Codigo de Conservacion', null=True),
        ),
    ]
