# Generated by Django 4.2 on 2023-07-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0085_estadocuentadetalle_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasamulta',
            name='codigo',
            field=models.TextField(blank=True, help_text='Codigo de la Tasa Multa', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tasamulta',
            name='detalle',
            field=models.TextField(blank=True, help_text='Información extra. en caso de un artoculo especifico de la ordenanza', null=True),
        ),
        migrations.AlterField(
            model_name='tipoflujo',
            name='codigo',
            field=models.TextField(blank=True, help_text='Codigo del Tipo de Flujo', null=True, unique=True),
        ),
    ]
