# Generated by Django 4.2 on 2023-07-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0086_alter_tasamulta_codigo_alter_tasamulta_detalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IC_Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de Acceso', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de Acceso', unique=True)),
                ('Periodo', models.PositiveIntegerField(blank=True, help_text='Orden del menu y de la opcion dentro de menu', null=True)),
                ('diainicio', models.PositiveIntegerField(blank=True, help_text='Orden del menu y de la opcion dentro de menu', null=True)),
                ('mesinicio', models.PositiveIntegerField(blank=True, help_text='Orden del menu y de la opcion dentro de menu', null=True)),
                ('diafin', models.PositiveIntegerField(blank=True, help_text='Orden del menu y de la opcion dentro de menu', null=True)),
                ('mesfin', models.PositiveIntegerField(blank=True, help_text='Orden del menu y de la opcion dentro de menu', null=True)),
                ('aplica', models.CharField(choices=[('C', 'Catastro'), ('V', 'Vehiculo'), ('P', 'Patente'), ('I', 'Industria y Comercio'), ('O', 'Otro')], default='C', help_text='Estado dela solicitud', max_length=1)),
            ],
        ),
    ]
