# Generated by Django 4.2 on 2023-07-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0087_ic_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ic_periodo',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='ic_periodo',
            name='Periodo',
            field=models.PositiveIntegerField(blank=True, help_text='Numero del periodo', null=True),
        ),
        migrations.AlterField(
            model_name='ic_periodo',
            name='descripcion',
            field=models.TextField(help_text='descripcion del Periodo', unique=True),
        ),
        migrations.AlterField(
            model_name='ic_periodo',
            name='diafin',
            field=models.TextField(blank=True, help_text='dia fin', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ic_periodo',
            name='diainicio',
            field=models.TextField(blank=True, help_text='dia inicio', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ic_periodo',
            name='mesfin',
            field=models.TextField(blank=True, help_text='Mes fin', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ic_periodo',
            name='mesinicio',
            field=models.TextField(blank=True, help_text='Mes inicio', max_length=2, null=True),
        ),
    ]
