# Generated by Django 4.2 on 2023-07-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0088_remove_ic_periodo_codigo_alter_ic_periodo_periodo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ic_periodo',
            old_name='Periodo',
            new_name='periodo',
        ),
    ]
