# Generated by Django 4.2 on 2023-07-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0089_rename_periodo_ic_periodo_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlativo',
            name='NumeroCalculoImpuesto',
            field=models.PositiveIntegerField(blank=True, help_text='Numero calculo de impuesto', null=True),
        ),
        migrations.AddField(
            model_name='correlativo',
            name='NumeroCalculoMulta',
            field=models.PositiveIntegerField(blank=True, help_text='Numero de calculo de multa', null=True),
        ),
        migrations.AddField(
            model_name='correlativo',
            name='NumeroCorreccionImpuesto',
            field=models.PositiveIntegerField(blank=True, help_text='Numero correccion impuesto Catastro', null=True),
        ),
        migrations.AlterField(
            model_name='correlativo',
            name='NumeroSolicitud',
            field=models.PositiveIntegerField(blank=True, help_text='Numero de Solicitud FLUJO', null=True),
        ),
        migrations.AlterField(
            model_name='estadocuenta',
            name='numero',
            field=models.TextField(help_text='Numero de Estado de Cuenta. Correlativo.NumeroEstadoCuenta', unique=True),
        ),
        migrations.AlterField(
            model_name='flujo',
            name='numero',
            field=models.TextField(help_text='Numero de Solicitud. Correlativo.NumeroSolicitud', unique=True),
        ),
        migrations.AlterField(
            model_name='ic_periodo',
            name='aplica',
            field=models.CharField(choices=[('C', 'Catastro'), ('V', 'Vehiculo'), ('P', 'Patente'), ('I', 'Industria y Comercio'), ('O', 'Otro')], default='C', help_text='Aplica a...', max_length=1),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='numero_expediente',
            field=models.TextField(help_text='Numero de expediente.Correlativo.ExpedienteCatastro', unique=True),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='numero',
            field=models.TextField(help_text='Numero de Liquidacion. Correlativo.NumeroLiquidacion', unique=True),
        ),
        migrations.AlterField(
            model_name='pagoestadocuenta',
            name='numero',
            field=models.TextField(help_text='Numero de pago. Correlativo.NumeroPago', unique=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='email_principal',
            field=models.TextField(help_text='correo 1'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='emaill_secundario',
            field=models.TextField(blank=True, help_text='correo 2', null=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nacionalidad',
            field=models.TextField(help_text='Nacinalidad'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombre',
            field=models.TextField(help_text='Nombre'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='numero_documento',
            field=models.TextField(help_text='Numero de documento', unique=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefono_principal',
            field=models.TextField(help_text='Numero de teléfono principal'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefono_secundario',
            field=models.TextField(blank=True, help_text='Numero de teléfono secundario', null=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='tipo_documento',
            field=models.TextField(help_text='Tipo de documento'),
        ),
    ]
