# Generated by Django 4.2 on 2023-07-23 12:45

import backend.models
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0090_correlativo_numerocalculoimpuesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IC_Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(help_text='Numero de pago', unique=True)),
                ('basecalculobs', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='base imponible del tributo en referencia', max_digits=22, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='suma de total_uso de ImpuestoDetalle', max_digits=22, null=True)),
                ('multa', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='IC_ImpuestoCargos.porcentaje donde codigo=multa', max_digits=22, null=True)),
                ('recargo', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='IC_ImpuestoCargos.porcentaje donde codigo=recargo', max_digits=22, null=True)),
                ('interes', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='IC_ImpuestoCargos.porcentaje donde codigo=interes', max_digits=22, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='Total', max_digits=22, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='descuento', max_digits=22, null=True)),
                ('grantotal', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='gran total', max_digits=22, null=True)),
                ('Factor', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='si es 1 es todo el año (4 periodos). Si es un periodo, el factor=0.75', max_digits=5, null=True)),
                ('estadocuenta', models.ForeignKey(help_text='ID Cabecera Estado de Cuenta', on_delete=django.db.models.deletion.PROTECT, to='backend.estadocuenta')),
                ('inmueble', models.ForeignKey(help_text='Inmueble', on_delete=django.db.models.deletion.PROTECT, to='backend.inmueble')),
                ('liquidacion', models.ForeignKey(help_text='ID Cabecera liquidacion', on_delete=django.db.models.deletion.PROTECT, to='backend.liquidacion')),
                ('zona', models.ForeignKey(blank=True, help_text='Zona !! Base para calculo', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.zona')),
            ],
        ),
        migrations.CreateModel(
            name='IC_ImpuestoCargos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo: multa, recargo, impuesto ', unique=True)),
                ('descripcion', models.TextField(help_text='Descripcion', unique=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='Porcentaje', max_digits=22, null=True)),
                ('habilitado', models.BooleanField(default=True, help_text='Esta activo?')),
                ('aplica', models.CharField(choices=[('C', 'Catastro'), ('V', 'Vehiculo'), ('P', 'Patente'), ('I', 'Industria y Comercio'), ('O', 'Otro')], default='C', help_text='Aplica a...', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='IC_ImpuestoCorrecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(help_text='Numero de Solicitud. Correlativo.NumeroCorreccionImpuesto', unique=True)),
                ('observaciones', models.TextField(blank=True, help_text='observaciones', null=True)),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='fecha de registro')),
                ('numerorecibo', models.TextField(blank=True, help_text='numero del recibo de pago como referencia', null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='monto cancelado según el recibo de pago', max_digits=22, null=True)),
                ('inmueble', models.ForeignKey(help_text='Inmueble', on_delete=django.db.models.deletion.PROTECT, to='backend.inmueble')),
            ],
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='pdf_documento',
            field=models.FileField(blank=True, help_text='Pdf del documento de registro', null=True, upload_to=backend.models.immuebles_path_doc),
        ),
        migrations.CreateModel(
            name='IC_ImpuestoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Descripcion', unique=True)),
                ('fechadesde', models.DateField(blank=True, help_text='fecha construccion')),
                ('fechahasta', models.DateField(blank=True, help_text='fecha construccion')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='Porcentaje de descuento', max_digits=22, null=True)),
                ('habilitado', models.BooleanField(default=True, help_text='Esta activo?')),
                ('aplica', models.CharField(choices=[('C', 'Catastro'), ('V', 'Vehiculo'), ('P', 'Patente'), ('I', 'Industria y Comercio'), ('O', 'Otro')], default='C', help_text='Aplica a...', max_length=1)),
                ('tipologia', models.ForeignKey(blank=True, help_text='tipologia asociado. Solo para Inmuebles. Si no tiene aplica a cualquier uso', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipologia')),
            ],
        ),
        migrations.CreateModel(
            name='IC_ImpuestoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Area en m2', max_digits=22)),
                ('alicuota_articulo41', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Alicuota', max_digits=22)),
                ('base', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='area x aliuota_articulo41', max_digits=22)),
                ('descuento', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='suma de descuentos (detalle en IC_ImpuestoDescuento)', max_digits=22)),
                ('total', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='(area x alicuota_articulo41)-descuento', max_digits=22)),
                ('sub_utilizado', models.BooleanField(default=False, help_text='subutilizado si o no')),
                ('IC_impuesto', models.ForeignKey(help_text='ID IC_Impuesto', on_delete=django.db.models.deletion.PROTECT, to='backend.ic_impuesto')),
                ('tipo', models.ForeignKey(blank=True, help_text='Tipo de Inmueble asociado para determinar si unifamiliar o multifamiliar', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipoinmueble')),
                ('tipologia', models.ForeignKey(blank=True, help_text='tipologia asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipologia')),
            ],
        ),
        migrations.CreateModel(
            name='IC_ImpuestoCorreccionesDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagensoporte', models.ImageField(blank=True, help_text='Imagen de soporte', null=True, upload_to=backend.models.correcciones_path)),
                ('IC_impuestocorrecciones', models.ForeignKey(help_text='ID Impuesto Correcciones', on_delete=django.db.models.deletion.PROTECT, to='backend.ic_impuestocorrecciones')),
            ],
        ),
    ]
