# Generated by Django 4.2 on 2023-07-23 23:31

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0091_ic_impuesto_ic_impuestocargos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IC_ImpuestoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Descripcion', unique=True)),
                ('fechadesde', models.DateField(blank=True, help_text='fecha construccion')),
                ('fechahasta', models.DateField(blank=True, help_text='fecha construccion')),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='Porcentaje de descuento', max_digits=22, null=True)),
                ('habilitado', models.BooleanField(default=True, help_text='Esta activo?')),
                ('aplica', models.CharField(choices=[('C', 'Catastro'), ('V', 'Vehiculo'), ('P', 'Patente'), ('I', 'Industria y Comercio'), ('O', 'Otro')], default='C', help_text='Aplica a...', max_length=1)),
                ('tipologia', models.ForeignKey(blank=True, help_text='tipologia asociado. Solo para Inmuebles. Si no tiene aplica a cualquier uso', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipologia')),
            ],
        ),
        migrations.RemoveField(
            model_name='ic_impuestoperiodo',
            name='aplica',
        ),
        migrations.RemoveField(
            model_name='ic_impuestoperiodo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='ic_impuestoperiodo',
            name='fechadesde',
        ),
        migrations.RemoveField(
            model_name='ic_impuestoperiodo',
            name='fechahasta',
        ),
        migrations.RemoveField(
            model_name='ic_impuestoperiodo',
            name='habilitado',
        ),
        migrations.RemoveField(
            model_name='ic_impuestoperiodo',
            name='porcentaje',
        ),
        migrations.RemoveField(
            model_name='ic_impuestoperiodo',
            name='tipologia',
        ),
        migrations.AddField(
            model_name='correlativo',
            name='NumeroIC_Impuesto',
            field=models.PositiveIntegerField(blank=True, help_text='Numero Impuesto Catastro', null=True),
        ),
        migrations.AddField(
            model_name='ic_impuestoperiodo',
            name='IC_impuesto',
            field=models.ForeignKey(blank=True, help_text='ID Impuesto Inmueble', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ic_impuesto'),
        ),
        migrations.AddField(
            model_name='ic_impuestoperiodo',
            name='IC_impuestocorrecciones',
            field=models.ForeignKey(blank=True, help_text='ID Impuesto Correcciones. Sin dato es no se ha pagado con ninguna correccion', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ic_impuestocorrecciones'),
        ),
        migrations.AddField(
            model_name='ic_impuestoperiodo',
            name='anio',
            field=models.PositiveIntegerField(blank=True, help_text='Año', null=True),
        ),
        migrations.AddField(
            model_name='ic_impuestoperiodo',
            name='inmueble',
            field=models.ForeignKey(default=1, help_text='Inmueble', on_delete=django.db.models.deletion.PROTECT, to='backend.inmueble'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ic_impuestoperiodo',
            name='pagoestadocuenta',
            field=models.ForeignKey(blank=True, help_text='ID Cabecera PAGO, Sin dato es no se ha pagado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.pagoestadocuenta'),
        ),
        migrations.AddField(
            model_name='ic_impuestoperiodo',
            name='periodo',
            field=models.ForeignKey(default=1, help_text='Periodo', on_delete=django.db.models.deletion.PROTECT, to='backend.ic_periodo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IC_ImpuestoDetalleDescuentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='Total. Segun la tipologia:IC_ImpuestoDetalle.base * TC_ImpuestoDescuentos.porcentaje', max_digits=22, null=True)),
                ('IC_impuestodescuento', models.ForeignKey(help_text='ID Impuesto Inmueble', on_delete=django.db.models.deletion.PROTECT, to='backend.ic_impuestodescuento')),
                ('IC_impuestodetalle', models.ForeignKey(help_text='ID Impuesto Inmueble', on_delete=django.db.models.deletion.PROTECT, to='backend.ic_impuestodetalle')),
            ],
        ),
    ]
