# Generated by Django 4.2 on 2023-07-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0092_ic_impuestodescuento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ic_impuestodescuento',
            name='fechadesde',
        ),
        migrations.RemoveField(
            model_name='ic_impuestodescuento',
            name='fechahasta',
        ),
        migrations.AddField(
            model_name='ic_impuestodescuento',
            name='diafin',
            field=models.TextField(blank=True, help_text='dia fin', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='ic_impuestodescuento',
            name='diainicio',
            field=models.TextField(blank=True, help_text='dia inicio', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='ic_impuestodescuento',
            name='mesfin',
            field=models.TextField(blank=True, help_text='Mes fin', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='ic_impuestodescuento',
            name='mesinicio',
            field=models.TextField(blank=True, help_text='Mes inicio', max_length=2, null=True),
        ),
    ]
