# Generated by Django 4.2 on 2023-07-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0093_remove_ic_impuestodescuento_fechadesde_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ic_impuestodescuento',
            name='diafin',
        ),
        migrations.RemoveField(
            model_name='ic_impuestodescuento',
            name='diainicio',
        ),
        migrations.RemoveField(
            model_name='ic_impuestodescuento',
            name='mesfin',
        ),
        migrations.RemoveField(
            model_name='ic_impuestodescuento',
            name='mesinicio',
        ),
        migrations.AddField(
            model_name='ic_impuestodescuento',
            name='fechadesde',
            field=models.DateField(blank=True, help_text='fecha construccion', null=True),
        ),
        migrations.AddField(
            model_name='ic_impuestodescuento',
            name='fechahasta',
            field=models.DateField(blank=True, help_text='fecha construccion', null=True),
        ),
    ]
