# Generated by Django 4.2 on 2023-07-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0094_remove_ic_impuestodescuento_diafin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ic_periodo',
            name='dias_gracia',
            field=models.PositiveIntegerField(blank=True, help_text='Dias a partir del diainicio que no paga multa', null=True),
        ),
    ]
