# Generated by Django 4.2 on 2023-07-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0095_ic_periodo_dias_gracia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ic_periodo',
            name='fechadesde',
            field=models.DateField(blank=True, help_text='fecha Desde donde valida si aplica el descuento', null=True),
        ),
        migrations.AddField(
            model_name='ic_periodo',
            name='fechahasta',
            field=models.DateField(blank=True, help_text='fecha Hasta donde valida si aplica el descuento', null=True),
        ),
        migrations.AlterField(
            model_name='ic_impuestodescuento',
            name='fechadesde',
            field=models.DateField(blank=True, help_text='fecha Desde donde valida si aplica el descuento', null=True),
        ),
        migrations.AlterField(
            model_name='ic_impuestodescuento',
            name='fechahasta',
            field=models.DateField(blank=True, help_text='fecha Hasta donde valida si aplica el descuento', null=True),
        ),
    ]
