# Generated by Django 4.2 on 2023-07-26 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0096_ic_periodo_fechadesde_ic_periodo_fechahasta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ic_impuestoperiodo',
            name='IC_impuesto',
        ),
    ]
