# Generated by Django 4.2 on 2023-07-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0097_remove_ic_impuestoperiodo_ic_impuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ic_impuestodetalle',
            name='IC_ImpuestoPeriodo',
            field=models.ForeignKey(blank=True, help_text='ID IC_ImpuestoPeriodo. Por este D al momento de pagar esta Liquidacion entonces marco el periodo en IC_ImpuestoPeriodo como cancelado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ic_impuestoperiodo'),
        ),
    ]
