# Generated by Django 4.2 on 2023-07-26 23:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0098_ic_impuestodetalle_ic_impuestoperiodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ic_impuestodetalledescuentos',
            name='base',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='Base de calculo', max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='ic_impuestodetalledescuentos',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='Porcentaje de descuento', max_digits=22, null=True),
        ),
    ]
