# Generated by Django 4.2 on 2023-07-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0099_ic_impuestodetalledescuentos_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ic_impuesto',
            name='Factor',
        ),
    ]
