# Generated by Django 4.2 on 2023-07-27 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0100_remove_ic_impuesto_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ic_impuesto',
            name='estadocuenta',
            field=models.ForeignKey(blank=True, help_text='ID Cabecera Estado de Cuenta', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.estadocuenta'),
        ),
        migrations.AlterField(
            model_name='ic_impuesto',
            name='liquidacion',
            field=models.ForeignKey(blank=True, help_text='ID Cabecera liquidacion', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.liquidacion'),
        ),
    ]
