# Generated by Django 4.2 on 2023-08-02 15:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0101_alter_ic_impuesto_estadocuenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ic_impuesto',
            name='aniopago',
            field=models.PositiveIntegerField(blank=True, help_text='Año hasta donde se calculo el impuesto', null=True),
        ),
        migrations.AddField(
            model_name='ic_impuesto',
            name='periodopago',
            field=models.PositiveIntegerField(blank=True, help_text='Periodo  hasta donde se calculo el impuesto', null=True),
        ),
        migrations.AlterField(
            model_name='ic_impuesto',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='descuento????', max_digits=22, null=True),
        ),
    ]
