# Generated by Django 4.2 on 2023-08-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0102_ic_impuesto_aniopago_ic_impuesto_periodopago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='aplica',
            field=models.CharField(choices=[('C', 'Inmuebles Urbanos'), ('A', 'Actividades económicas'), ('V', 'Vehiculos'), ('P', 'Propaganda y publicidad'), ('X', 'Todos')], default='X', help_text='A que tipo de sector aplica', max_length=1),
        ),
        migrations.AddField(
            model_name='tipoflujo',
            name='aplica',
            field=models.CharField(choices=[('C', 'Catastro'), ('V', 'Vehiculo'), ('P', 'Patente'), ('I', 'Industria y Comercio'), ('O', 'Otro')], default='O', help_text='A que tipo de sector aplica', max_length=1),
        ),
    ]
