# Generated by Django 4.2 on 2023-08-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0103_departamento_aplica_tipoflujo_aplica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ic_impuestocargos',
            name='aplica',
            field=models.CharField(choices=[('C', 'Inmuebles Urbanos'), ('A', 'Actividades económicas'), ('V', 'Vehiculos'), ('P', 'Propaganda y publicidad'), ('X', 'Todos')], default='X', help_text='A que tipo de sector aplica', max_length=1),
        ),
        migrations.AlterField(
            model_name='ic_impuestodescuento',
            name='aplica',
            field=models.CharField(choices=[('C', 'Inmuebles Urbanos'), ('A', 'Actividades económicas'), ('V', 'Vehiculos'), ('P', 'Propaganda y publicidad'), ('X', 'Todos')], default='X', help_text='A que tipo de sector aplica', max_length=1),
        ),
        migrations.AlterField(
            model_name='ic_periodo',
            name='aplica',
            field=models.CharField(choices=[('C', 'Inmuebles Urbanos'), ('A', 'Actividades económicas'), ('V', 'Vehiculos'), ('P', 'Propaganda y publicidad'), ('X', 'Todos')], default='X', help_text='A que tipo de sector aplica', max_length=1),
        ),
        migrations.AlterField(
            model_name='tasamulta',
            name='aplica',
            field=models.CharField(choices=[('C', 'Inmuebles Urbanos'), ('A', 'Actividades económicas'), ('V', 'Vehiculos'), ('P', 'Propaganda y publicidad'), ('X', 'Todos')], default='X', help_text='A que tipo de sector aplica', max_length=1),
        ),
        migrations.AlterField(
            model_name='tipoflujo',
            name='aplica',
            field=models.CharField(choices=[('C', 'Inmuebles Urbanos'), ('A', 'Actividades económicas'), ('V', 'Vehiculos'), ('P', 'Propaganda y publicidad'), ('X', 'Todos')], default='X', help_text='A que tipo de sector aplica', max_length=1),
        ),
    ]
