# Generated by Django 4.2 on 2023-08-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0104_alter_ic_impuestocargos_aplica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueblepropietarios',
            name='multa_articulo_101',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='habilitado',
            field=models.BooleanField(default=True, help_text='Esta activo?'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='inscripcion_paga',
            field=models.BooleanField(default=False, help_text='True desde use_case de crear pago cuando se cancele el flujo de Inscripcion de Inmueble'),
        ),
        migrations.AddField(
            model_name='inmueblepropietarios',
            name='modificacion_paga',
            field=models.BooleanField(default=False, help_text='True desde use_case de crear pago cuando se cancele el flujo de cambio de propietario'),
        ),
    ]
