# Generated by Django 4.2 on 2023-08-08 16:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0105_remove_inmueblepropietarios_multa_articulo_101_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ic_periodo',
            name='diafin',
        ),
        migrations.RemoveField(
            model_name='ic_periodo',
            name='diainicio',
        ),
        migrations.RemoveField(
            model_name='ic_periodo',
            name='mesfin',
        ),
        migrations.RemoveField(
            model_name='ic_periodo',
            name='mesinicio',
        ),
        migrations.CreateModel(
            name='IC_MultaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Area en m2', max_digits=22)),
                ('alicuota_articulo41', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Alicuota', max_digits=22)),
                ('base', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='area x aliuota_articulo41', max_digits=22)),
                ('descuento', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='suma de descuentos (detalle en IC_ImpuestoDescuento)', max_digits=22)),
                ('total', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='(area x alicuota_articulo41)-descuento', max_digits=22)),
                ('sub_utilizado', models.BooleanField(default=False, help_text='subutilizado si o no')),
                ('IC_ImpuestoPeriodo', models.ForeignKey(blank=True, help_text='ID IC_ImpuestoPeriodo. Por este D al momento de pagar esta Liquidacion entonces marco el periodo en IC_ImpuestoPeriodo como cancelado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ic_impuestoperiodo')),
                ('IC_impuesto', models.ForeignKey(help_text='ID IC_Impuesto', on_delete=django.db.models.deletion.PROTECT, to='backend.ic_impuesto')),
                ('tipo', models.ForeignKey(blank=True, help_text='Tipo de Inmueble asociado para determinar si unifamiliar o multifamiliar', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipoinmueble')),
                ('tipologia', models.ForeignKey(blank=True, help_text='tipologia asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipologia')),
            ],
        ),
        migrations.CreateModel(
            name='IC_Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(help_text='Numero de pago', unique=True)),
                ('basecalculobs', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='base imponible del tributo en referencia', max_digits=22, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='suma de total_uso de ImpuestoDetalle', max_digits=22, null=True)),
                ('multa', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='IC_ImpuestoCargos.porcentaje donde codigo=multa', max_digits=22, null=True)),
                ('recargo', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='IC_ImpuestoCargos.porcentaje donde codigo=recargo', max_digits=22, null=True)),
                ('interes', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='IC_ImpuestoCargos.porcentaje donde codigo=interes', max_digits=22, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='Total', max_digits=22, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='descuento????', max_digits=22, null=True)),
                ('grantotal', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='gran total', max_digits=22, null=True)),
                ('aniopago', models.PositiveIntegerField(blank=True, help_text='Año hasta donde se calculo el impuesto', null=True)),
                ('periodopago', models.PositiveIntegerField(blank=True, help_text='Periodo  hasta donde se calculo el impuesto', null=True)),
                ('estadocuenta', models.ForeignKey(blank=True, help_text='ID Cabecera Estado de Cuenta', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.estadocuenta')),
                ('inmueble', models.ForeignKey(help_text='Inmueble', on_delete=django.db.models.deletion.PROTECT, to='backend.inmueble')),
                ('liquidacion', models.ForeignKey(blank=True, help_text='ID Cabecera liquidacion', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.liquidacion')),
                ('zona', models.ForeignKey(blank=True, help_text='Zona !! Base para calculo', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.zona')),
            ],
        ),
    ]
