# Generated by Django 4.2 on 2023-08-10 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0109_alter_inmueblevaloracionconstruccion_tipologia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueblevaloracionconstruccion',
            name='tipo',
            field=models.ForeignKey(help_text='Tipo de Inmueble asociado para determinar si unifamiliar o multifamiliar', on_delete=django.db.models.deletion.PROTECT, to='backend.tipoinmueble'),
        ),
        migrations.AlterField(
            model_name='inmueblevaloracionconstruccion',
            name='tipologia',
            field=models.ForeignKey(help_text='tipologia asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.tipologia'),
        ),
    ]
