# Generated by Django 4.2 on 2023-08-16 16:04

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0110_alter_inmueblevaloracionconstruccion_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AE_ActividadEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Código de clasificación actividad económica')),
                ('descripcion', models.TextField(help_text='Descripcion', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AE_ActividadEconomicaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Código de clasificación actividad económica')),
                ('descripcion', models.TextField(help_text='Descripcion', unique=True)),
                ('alicuota', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Alicuota', max_digits=22)),
                ('minimo_tributable_mensual', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='este  impuesto no puede ser superior a este % de los ingresos brutos obtenidos en el mes', max_digits=22)),
                ('minimo_tributable_anual', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='este  impuesto no puede ser superior a este % de los ingresos brutos obtenidos en el año', max_digits=22)),
                ('observaciones', models.TextField(blank=True, help_text='observaciones', null=True)),
                ('AE_actividadeconomica', models.ForeignKey(blank=True, help_text='Id TipoFlujo', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ae_actividadeconomica')),
            ],
        ),
        migrations.CreateModel(
            name='AE_Patente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.TextField(help_text='Correlativo.NumeroAE_Patente para tipo_patente T o D, Correlativo.NumeroAE_Patente_Generica para tipo_patente G', unique=True)),
                ('tipo_patente', models.CharField(choices=[('T', 'Temporal'), ('D', 'Definitiva'), ('G', 'Genérica')], default='T', help_text='Tpo de patente o licencia', max_length=1)),
                ('numero_documento_representante', models.TextField(help_text='Numero de documento (RIF)', unique=True)),
                ('nombre_representante', models.TextField(help_text='Nombre o razon social')),
                ('cargo_representante', models.TextField(help_text='Cargo')),
                ('telefono_secundario', models.TextField(blank=True, help_text='Numero de teléfono secundario', null=True)),
                ('horario_desde', models.TextField(help_text='horario de trabajo desde formato militar')),
                ('horario_hasta', models.TextField(help_text='horario de trabajo hasta: formato militar')),
                ('nro_inmuebles', models.PositiveIntegerField(blank=True, help_text='Numero de inmuebles', null=True)),
                ('nro_solicitud', models.PositiveIntegerField(blank=True, help_text='Numero de solicitud', null=True)),
                ('nro_tomo', models.PositiveIntegerField(blank=True, help_text='Numero de tomo', null=True)),
                ('periodo', models.ForeignKey(help_text='Periodo de inscripcion', on_delete=django.db.models.deletion.PROTECT, to='backend.ic_periodo')),
            ],
        ),
        migrations.AddField(
            model_name='correlativo',
            name='NumeroAE_Patente',
            field=models.PositiveIntegerField(blank=True, help_text='Numero de licencia o patente de Indistria y comercio', null=True),
        ),
        migrations.AddField(
            model_name='correlativo',
            name='NumeroAE_Patente_Generica',
            field=models.PositiveIntegerField(blank=True, help_text='Numero de licencia o patente de Indistria y comercio genérica', null=True),
        ),
        migrations.AlterField(
            model_name='ic_impuesto',
            name='numero',
            field=models.TextField(help_text='Correlativo.NumeroIC_Impuesto', unique=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombre',
            field=models.TextField(help_text='Nombre o razon social'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='numero_documento',
            field=models.TextField(help_text='Numero de documento (RIF)', unique=True),
        ),
        migrations.CreateModel(
            name='AE_Patente_ActividadEconomica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AE_actividadeconomicadetalle', models.ForeignKey(blank=True, help_text='Id AE_ActividadEconomicaDetalle', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ae_actividadeconomicadetalle')),
                ('AE_patente', models.ForeignKey(blank=True, help_text='Id AE_patente', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ae_patente')),
            ],
        ),
        migrations.AddField(
            model_name='ae_patente',
            name='propietario',
            field=models.ForeignKey(blank=True, help_text='ID Propietario', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.propietario'),
        ),
    ]
