# Generated by Django 4.2 on 2023-08-22 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0112_ae_actividadeconomicadetalle_porcentaje_maximo_ingresos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ae_patente',
            name='habilitado',
            field=models.BooleanField(default=True, help_text='Licencia activa si o no'),
        ),
        migrations.AddField(
            model_name='ae_patente',
            name='inmueble',
            field=models.ForeignKey(blank=True, help_text='Inmueble', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.inmueble'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='anio',
            field=models.PositiveIntegerField(blank=True, help_text='Año que adeuda', null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='periodo',
            field=models.ForeignKey(blank=True, help_text='Periodo que adeuda', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ic_periodo'),
        ),
    ]
