# Generated by Django 4.2 on 2023-08-23 11:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0113_ae_patente_habilitado_ae_patente_inmueble_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(blank=True, help_text='Año', null=True)),
                ('mes', models.PositiveIntegerField(blank=True, help_text='Mes', null=True)),
                ('tasa', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Tasa', max_digits=6)),
                ('habilitado', models.BooleanField(default=True, help_text='Esta activo?')),
            ],
        ),
    ]
