# Generated by Django 4.2 on 2023-08-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0114_tasainteres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ae_patente',
            old_name='telefono_secundario',
            new_name='telefono',
        ),
        migrations.AddField(
            model_name='ae_patente',
            name='anio',
            field=models.PositiveIntegerField(blank=True, help_text='Año', null=True),
        ),
    ]
