# Generated by Django 4.2 on 2023-08-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0115_rename_telefono_secundario_ae_patente_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoestadocuentadetalle',
            name='nro_aprobacion',
            field=models.TextField(blank=True, help_text='numero de aprobacion (debito)', null=True),
        ),
        migrations.AddField(
            model_name='pagoestadocuentadetalle',
            name='nro_lote',
            field=models.TextField(blank=True, help_text='numero de lote (debito)', null=True),
        ),
        migrations.AlterField(
            model_name='pagoestadocuentadetalle',
            name='nro_referencia',
            field=models.TextField(blank=True, help_text='numero de referencia (debito, trasferencia y nota de credito)', null=True),
        ),
    ]
