# Generated by Django 4.2 on 2023-08-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0117_correlativo_numeronotacredito_tipopago_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='caja',
            field=models.PositiveIntegerField(blank=True, help_text='Numero de Caja en caso que el perfil sea de cajero', null=True),
        ),
    ]
