# Generated by Django 4.2 on 2023-08-29 22:39

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0119_pagoestadocuenta_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoestadocuenta',
            name='monto_cxc',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='monto de la factura, la diferencia de lo pagado de mas se usa para crear la nota de crédito', max_digits=22),
        ),
        migrations.AlterField(
            model_name='pagoestadocuenta',
            name='monto',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='total pagado', max_digits=22),
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeronotacredito', models.TextField(help_text='Numero de nota de credito', unique=True)),
                ('observacion', models.TextField(blank=True, help_text='observacion', null=True)),
                ('fecha', models.DateTimeField(blank=True, help_text='Fecha creacion', null=True)),
                ('monto', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='monto original de la nota de credito', max_digits=22)),
                ('saldo', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='saldo de la nota de credito', max_digits=22)),
                ('propietario', models.ForeignKey(help_text='Id Propietario', on_delete=django.db.models.deletion.PROTECT, to='backend.propietario')),
            ],
        ),
    ]
