# Generated by Django 4.2 on 2023-08-29 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0120_pagoestadocuenta_monto_cxc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='tipopago',
            field=models.ForeignKey(blank=True, help_text='Id Tipo Pago', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipopago'),
        ),
    ]
