# Generated by Django 4.2 on 2023-08-31 12:13

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0121_notacredito_tipopago'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInmuebleValoracionConstruccion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sub_utilizado', models.BooleanField(default=False, help_text='subutilizado si o no')),
                ('fecha_construccion', models.DateField(blank=True, help_text='fecha construccion', null=True)),
                ('area', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Area en m2', max_digits=22)),
                ('valor', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='valor', max_digits=22)),
                ('depreciacion', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='depreciacion', max_digits=22)),
                ('valor_actual', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='valor', max_digits=22)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inmueblevaloracionterreno', models.ForeignKey(blank=True, db_constraint=False, help_text='Id inmueble_terreno asociado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.inmueblevaloracionterreno')),
                ('tipo', models.ForeignKey(blank=True, db_constraint=False, help_text='Tipo de Inmueble asociado para determinar si unifamiliar o multifamiliar', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.tipoinmueble')),
                ('tipologia', models.ForeignKey(blank=True, db_constraint=False, help_text='tipologia asociado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.tipologia')),
            ],
            options={
                'verbose_name': 'historical inmueble valoracion construccion',
                'verbose_name_plural': 'historical inmueble valoracion construccions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
