# Generated by Django 4.2 on 2023-08-31 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0123_historicalinmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='urbanizacion',
            name='zona',
            field=models.ForeignKey(blank=True, help_text='Zona !! Base para calculo', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.zona'),
        ),
    ]
