# Generated by Django 4.2 on 2023-09-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0124_urbanizacion_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='codigo',
            field=models.TextField(blank=True, help_text='Codigo del banco', null=True),
        ),
    ]
