# Generated by Django 4.2 on 2023-09-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0126_alter_sector_codigo_alter_sector_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manzana',
            options={'ordering': ['sector', 'codigo']},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['ambito', 'codigo']},
        ),
        migrations.AlterField(
            model_name='manzana',
            name='codigo',
            field=models.TextField(help_text='Codigo de la Manzana'),
        ),
        migrations.AlterUniqueTogether(
            name='manzana',
            unique_together={('sector', 'codigo')},
        ),
    ]
