# Generated by Django 4.2 on 2023-09-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0128_alter_parcela_options_alter_parcela_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subparcela',
            options={'ordering': ['parcela', 'codigo']},
        ),
        migrations.AlterField(
            model_name='subparcela',
            name='codigo',
            field=models.TextField(help_text='Codigo de la SubParcela'),
        ),
        migrations.AlterUniqueTogether(
            name='subparcela',
            unique_together={('parcela', 'codigo')},
        ),
    ]
