# Generated by Django 4.2 on 2023-09-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0129_alter_subparcela_options_alter_subparcela_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urbanizacion',
            options={'ordering': ['sector', 'codigo']},
        ),
        migrations.AddField(
            model_name='urbanizacion',
            name='codigo',
            field=models.TextField(blank=True, help_text='Codigo de la urbanizacion', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='urbanizacion',
            unique_together={('sector', 'codigo')},
        ),
    ]
