# Generated by Django 4.2 on 2023-09-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0130_alter_urbanizacion_options_urbanizacion_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urbanizacion',
            name='codigo',
            field=models.TextField(blank=True, help_text='Codigo de la avenida', null=True),
        ),
    ]
