# Generated by Django 4.2 on 2023-09-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0131_alter_urbanizacion_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='direccion',
            field=models.TextField(blank=True, help_text='Direccion', null=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nacionalidad',
            field=models.TextField(default='V', help_text='Nacinalidad'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='tipo_documento',
            field=models.TextField(default='R', help_text='Tipo de documento: R=RIF'),
        ),
    ]
