# Generated by Django 4.2 on 2023-09-11 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0132_propietario_direccion_alter_propietario_nacionalidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conjuntoresidencial',
            options={'ordering': ['urbanizacion', 'codigo']},
        ),
        migrations.AddField(
            model_name='conjuntoresidencial',
            name='codigo',
            field=models.TextField(default='S-N', help_text='Codigo ConjuntoResidencial'),
        ),
        migrations.AlterField(
            model_name='conjuntoresidencial',
            name='urbanizacion',
            field=models.ForeignKey(help_text='Urbanizacion/barrio asociada', on_delete=django.db.models.deletion.PROTECT, to='backend.urbanizacion'),
        ),
        migrations.AlterUniqueTogether(
            name='conjuntoresidencial',
            unique_together={('urbanizacion', 'codigo')},
        ),
    ]
