# Generated by Django 4.2 on 2023-09-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0133_alter_conjuntoresidencial_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edificio',
            name='urbanizacion',
        ),
        migrations.AddField(
            model_name='edificio',
            name='codigo',
            field=models.TextField(default='S-N', help_text='Codigo Edificio'),
        ),
    ]
