# Generated by Django 4.2 on 2023-09-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0134_remove_edificio_urbanizacion_edificio_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edificio',
            options={'ordering': ['conjunto_residencial', 'codigo']},
        ),
        migrations.AlterUniqueTogether(
            name='edificio',
            unique_together={('conjunto_residencial', 'codigo')},
        ),
    ]
