# Generated by Django 4.2 on 2023-09-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0135_alter_edificio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edificio',
            options={'ordering': ['conjuntoresidencial', 'codigo']},
        ),
        migrations.AlterModelOptions(
            name='torre',
            options={'ordering': ['conjuntoresidencial', 'codigo']},
        ),
        migrations.RenameField(
            model_name='edificio',
            old_name='conjunto_residencial',
            new_name='conjuntoresidencial',
        ),
        migrations.RenameField(
            model_name='torre',
            old_name='conjunto_residencial',
            new_name='conjuntoresidencial',
        ),
        migrations.AddField(
            model_name='torre',
            name='codigo',
            field=models.TextField(default='S-N', help_text='Codigo Edificio'),
        ),
        migrations.AlterUniqueTogether(
            name='edificio',
            unique_together={('conjuntoresidencial', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='torre',
            unique_together={('conjuntoresidencial', 'codigo')},
        ),
        migrations.RemoveField(
            model_name='torre',
            name='urbanizacion',
        ),
    ]
