# Generated by Django 4.2 on 2023-09-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0136_alter_edificio_options_alter_torre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjuntoresidencial',
            name='nombre',
            field=models.TextField(help_text='nombre del conjunto residencial'),
        ),
        migrations.AlterField(
            model_name='edificio',
            name='nombre',
            field=models.TextField(help_text='nombre del Edificio'),
        ),
        migrations.AlterField(
            model_name='torre',
            name='codigo',
            field=models.TextField(default='S-N', help_text='Codigo Torre'),
        ),
        migrations.AlterField(
            model_name='torre',
            name='nombre',
            field=models.TextField(help_text='nombre de la Torre'),
        ),
    ]
