# Generated by Django 4.2 on 2023-09-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0137_alter_conjuntoresidencial_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avenida',
            name='tipo',
            field=models.CharField(choices=[('1', 'Una Via'), ('2', 'Doble Via'), ('3', 'Colateral'), ('4', 'Arterial')], default='1', help_text='tipo de avenida', max_length=1),
        ),
        migrations.AlterField(
            model_name='calle',
            name='tipo',
            field=models.CharField(choices=[('1', 'Una Via'), ('2', 'Doble Via'), ('3', 'Colateral'), ('4', 'Arterial')], default='1', help_text='tipo calle', max_length=1),
        ),
    ]
