# Generated by Django 4.2 on 2023-09-13 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0138_alter_avenida_tipo_alter_calle_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueblevaloracionterreno',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Tipo de Inmueble asociado para determinar si unifamiliar o multifamiliar', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipoinmueble'),
        ),
    ]
