# Generated by Django 4.2 on 2023-09-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0139_inmueblevaloracionterreno_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinmueblevaloracionconstruccion',
            name='aplica',
            field=models.CharField(default='C', help_text='CONSTRUCCION', max_length=1),
        ),
        migrations.AddField(
            model_name='inmueblevaloracionconstruccion',
            name='aplica',
            field=models.CharField(default='C', help_text='CONSTRUCCION', max_length=1),
        ),
        migrations.AddField(
            model_name='inmueblevaloracionterreno',
            name='aplica',
            field=models.CharField(default='T', help_text='TERRENO', max_length=1),
        ),
    ]
