# Generated by Django 4.2 on 2023-09-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0140_historicalinmueblevaloracionconstruccion_aplica_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'ordering': ['modulo__menu', '-modulo__es_menu', '-modulo__titulo']},
        ),
    ]
