# Generated by Django 4.2 on 2023-09-28 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0141_alter_permiso_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, help_text='tipo_documento asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipodocumento'),
        ),
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='tipo_especial',
            field=models.ForeignKey(blank=True, help_text='tipo_especial asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipoespecial'),
        ),
    ]
