# Generated by Django 4.2 on 2023-10-05 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0144_exceldocumentlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinmueblevaloracionconstruccion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalinmueblevaloracionconstruccion',
            name='inmueblevaloracionterreno',
        ),
        migrations.RemoveField(
            model_name='historicalinmueblevaloracionconstruccion',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='historicalinmueblevaloracionconstruccion',
            name='tipologia',
        ),
        migrations.DeleteModel(
            name='HistoricalInmueble',
        ),
        migrations.DeleteModel(
            name='HistoricalInmuebleValoracionConstruccion',
        ),
    ]
