# Generated by Django 4.2 on 2023-10-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0145_remove_historicalinmueblevaloracionconstruccion_history_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'ordering': ['perfil__usuario__username', 'modulo__menu', '-modulo__es_menu', '-modulo__titulo']},
        ),
        migrations.AddField(
            model_name='tipoflujo',
            name='carandai',
            field=models.BooleanField(default=True, help_text='genera flujo?'),
        ),
        migrations.AlterField(
            model_name='tipoflujo',
            name='aplica',
            field=models.CharField(choices=[('C', 'Inmuebles Urbanos'), ('I', 'Catasro'), ('A', 'Actividades económicas'), ('V', 'Vehiculos'), ('P', 'Propaganda y publicidad'), ('X', 'Todos')], default='X', help_text='A que tipo de sector aplica', max_length=1),
        ),
    ]
