# Generated by Django 4.2 on 2023-10-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0146_alter_permiso_options_tipoflujo_carandai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoflujo',
            name='aplica',
            field=models.CharField(choices=[('C', 'Inmuebles Urbanos'), ('I', 'Catastro'), ('A', 'Actividades económicas'), ('V', 'Vehiculos'), ('P', 'Propaganda y publicidad'), ('X', 'Todos')], default='X', help_text='A que tipo de sector aplica', max_length=1),
        ),
    ]
