# Generated by Django 4.2 on 2023-10-29 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0148_motivoanulacionpago_pagoestadocuenta_anula_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='pagoestadocuenta',
            field=models.ForeignKey(blank=True, help_text='Id Pago Liquidacion', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.pagoestadocuenta'),
        ),
    ]
