# Generated by Django 4.2 on 2023-10-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0149_notacredito_pagoestadocuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocuenta',
            name='ReportePdf',
            field=models.FileField(blank=True, help_text='PDF EstadoCuenta', null=True, upload_to='EstadoCuenta/'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='ReportePdf',
            field=models.FileField(blank=True, help_text='PDF PreFactura', null=True, upload_to='PreFactura/'),
        ),
        migrations.AddField(
            model_name='pagoestadocuenta',
            name='ReportePdf',
            field=models.FileField(blank=True, help_text='PDF PagoEstadoCuenta', null=True, upload_to='PagoEstadoCuenta/'),
        ),
    ]
