# Generated by Django 4.2 on 2023-11-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0150_estadocuenta_reportepdf_liquidacion_reportepdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancocuenta',
            name='codigocuenta',
            field=models.TextField(blank=True, help_text='codigo de Cuenta', null=True),
        ),
    ]
