# Generated by Django 4.2 on 2023-11-01 21:07

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0151_bancocuenta_codigocuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorridasBancarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha creacion')),
                ('referencia', models.TextField(help_text='referencia')),
                ('descripcion', models.TextField(help_text='descripcion')),
                ('monto', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='monto original de la nota de credito', max_digits=22)),
                ('situado', models.CharField(choices=[('R', 'Situado Regional'), ('N', 'Situado Nacional'), ('I', 'Interes'), ('D', 'Deposito'), ('T', 'Transferencia')], default='T', help_text='Tipo de transaccion', max_length=1)),
                ('bancocuenta', models.ForeignKey(help_text='ID Banco', on_delete=django.db.models.deletion.PROTECT, to='backend.bancocuenta')),
            ],
        ),
    ]
