# Generated by Django 4.2 on 2023-11-01 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0152_corridasbancarias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corridasbancarias',
            options={'ordering': ['bancocuenta', 'fecha', 'referencia', 'monto']},
        ),
        migrations.AlterUniqueTogether(
            name='corridasbancarias',
            unique_together={('bancocuenta', 'fecha', 'referencia', 'monto')},
        ),
    ]
