# Generated by Django 4.2 on 2023-11-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0153_alter_corridasbancarias_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corridasbancarias',
            name='fechacreacion',
            field=models.DateTimeField(blank=True, help_text='Fecha registro error', null=True),
        ),
    ]
