# Generated by Django 4.2 on 2023-12-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0154_corridasbancarias_fechacreacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlativo',
            name='Logo1',
            field=models.ImageField(blank=True, help_text='Logo 1 para reporte', null=True, upload_to='Logos/'),
        ),
        migrations.AddField(
            model_name='correlativo',
            name='Logo2',
            field=models.ImageField(blank=True, help_text='Logo 2 para reporte', null=True, upload_to='Logos/'),
        ),
    ]
