# Generated by Django 4.2 on 2023-12-15 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0157_motivodesincorporacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='motivodesincorporacion',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tipodesincorporacion',
            field=models.ForeignKey(blank=True, help_text='Motivo Desincorporacion', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipodesincorporacion'),
        ),
        migrations.DeleteModel(
            name='MotivoDesincorporacion',
        ),
    ]
