# Generated by Django 4.2 on 2023-12-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0158_remove_inmueble_motivodesincorporacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='ReportePdfDesincorporacion',
            field=models.FileField(blank=True, help_text='PDF Desincorporacion', null=True, upload_to='Desincorporacion/'),
        ),
    ]
