# Generated by Django 4.2 on 2023-12-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0159_inmueble_reportepdfdesincorporacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='ReportePdfCedulaCatastral',
            field=models.FileField(blank=True, help_text='PDF Cedula catastral', null=True, upload_to='CedulaCatastral/'),
        ),
        migrations.AddField(
            model_name='tipologia',
            name='FinesFiscales',
            field=models.BooleanField(default=False, help_text='True es para fines fiscales(para impresion de cedula catastral)'),
        ),
    ]
