# Generated by Django 4.2 on 2023-12-19 13:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0161_inmueblepropiedad_valor_construccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='Area en m2', max_digits=22, null=True),
        ),
    ]
