# Generated by Django 4.2 on 2023-12-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0163_alter_urbanizacion_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='numero_casa',
            field=models.TextField(blank=True, help_text='numero_casa de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='numero_civico',
            field=models.TextField(blank=True, help_text='numero_civico de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='numero_piso',
            field=models.TextField(blank=True, help_text='numero_piso de expediente', null=True),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='telefono',
            field=models.TextField(blank=True, help_text='telefono de expediente', null=True),
        ),
    ]
