# Generated by Django 4.2 on 2023-12-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0164_alter_inmueble_numero_casa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ic_impuesto',
            old_name='aniopago',
            new_name='aniopagofin',
        ),
        migrations.RenameField(
            model_name='ic_impuesto',
            old_name='periodopago',
            new_name='periodopagofin',
        ),
        migrations.AddField(
            model_name='ic_impuesto',
            name='aniopagoini',
            field=models.PositiveIntegerField(blank=True, help_text='Año hasta donde se calculo el impuesto', null=True),
        ),
        migrations.AddField(
            model_name='ic_impuesto',
            name='periodopagoini',
            field=models.PositiveIntegerField(blank=True, help_text='Periodo  hasta donde se calculo el impuesto', null=True),
        ),
    ]
