# Generated by Django 4.2 on 2023-12-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0165_rename_aniopago_ic_impuesto_aniopagofin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ic_impuesto',
            name='inmueble',
        ),
    ]
