# Generated by Django 4.2 on 2023-12-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0166_remove_ic_impuesto_inmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='ic_impuestodetalle',
            name='multa',
            field=models.BooleanField(default=False, help_text='Aplico multa?'),
        ),
    ]
