# Generated by Django 4.2 on 2023-12-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0167_ic_impuestodetalle_multa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ic_impuestodetalle',
            name='IC_ImpuestoPeriodo',
        ),
        migrations.AddField(
            model_name='ic_impuestodetalle',
            name='anio',
            field=models.PositiveIntegerField(blank=True, help_text='Año de proceso', null=True),
        ),
        migrations.AddField(
            model_name='ic_impuestodetalle',
            name='periodo',
            field=models.ForeignKey(blank=True, help_text='Periodo de proceso', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ic_periodo'),
        ),
    ]
