# Generated by Django 4.2 on 2023-12-24 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0168_remove_ic_impuestodetalle_ic_impuestoperiodo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ic_impuestodetalledescuentos',
            name='IC_impuestodetalle',
        ),
        migrations.AddField(
            model_name='ic_impuestodetalledescuentos',
            name='IC_impuesto',
            field=models.ForeignKey(blank=True, help_text='ID IC_Impuesto', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ic_impuesto'),
        ),
        migrations.AddField(
            model_name='ic_impuestodetalledescuentos',
            name='anio',
            field=models.PositiveIntegerField(blank=True, help_text='Año de proceso', null=True),
        ),
        migrations.AddField(
            model_name='ic_impuestodetalledescuentos',
            name='periodo',
            field=models.ForeignKey(blank=True, help_text='Periodo de proceso', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ic_periodo'),
        ),
        migrations.AddField(
            model_name='ic_impuestodetalledescuentos',
            name='tipologia',
            field=models.ForeignKey(blank=True, help_text='tipologia asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipologia'),
        ),
        migrations.AlterField(
            model_name='ic_impuestodetalledescuentos',
            name='IC_impuestodescuento',
            field=models.ForeignKey(blank=True, help_text='ID Impuesto Inmueble', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ic_impuestodescuento'),
        ),
    ]
