# Generated by Django 4.2 on 2023-12-24 00:31

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0169_remove_ic_impuestodetalledescuentos_ic_impuestodetalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IC_ImpuestoDetalleMora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(blank=True, help_text='Año de proceso', null=True)),
                ('mes', models.PositiveIntegerField(blank=True, help_text='Mes de proceso', null=True)),
                ('tasa', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='tasa', max_digits=22)),
                ('dias', models.PositiveIntegerField(blank=True, help_text='dias', null=True)),
                ('moramensual', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='moramensual', max_digits=22)),
                ('interesmensual', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='interesmensual', max_digits=22)),
                ('IC_impuesto', models.ForeignKey(help_text='ID IC_Impuesto', on_delete=django.db.models.deletion.PROTECT, to='backend.ic_impuesto')),
            ],
        ),
    ]
