# Generated by Django 4.2 on 2023-12-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0170_ic_impuestodetallemora'),
    ]

    operations = [
        migrations.AddField(
            model_name='ic_impuestodescuento',
            name='prontopago',
            field=models.BooleanField(default=False, help_text='Es de pronto pago?, True si y valida la fecha con la fecha de sistema, false aplica por fecha y periododo'),
        ),
    ]
