# Generated by Django 4.2 on 2024-01-11 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0171_ic_impuestodescuento_prontopago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ae_patente_actividadeconomica',
            name='AE_actividadeconomicadetalle',
        ),
        migrations.AddField(
            model_name='ae_patente_actividadeconomica',
            name='AE_actividadeconomica',
            field=models.ForeignKey(blank=True, help_text='Id AE_ActividadEconomica', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ae_actividadeconomica'),
        ),
        migrations.AlterField(
            model_name='ae_actividadeconomicadetalle',
            name='AE_actividadeconomica',
            field=models.ForeignKey(blank=True, help_text='Id AE_ActividadEconomica', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ae_actividadeconomica'),
        ),
    ]
