# Generated by Django 4.2 on 2024-01-11 16:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0172_remove_ae_patente_actividadeconomica_ae_actividadeconomicadetalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ae_actividadeconomica',
            name='alicuota',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Alicuota', max_digits=22),
        ),
        migrations.AddField(
            model_name='ae_actividadeconomica',
            name='minimo_tributable_anual',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=22),
        ),
        migrations.AddField(
            model_name='ae_actividadeconomica',
            name='minimo_tributable_mensual',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=22),
        ),
        migrations.AddField(
            model_name='ae_actividadeconomica',
            name='observaciones',
            field=models.TextField(blank=True, help_text='observaciones', null=True),
        ),
        migrations.AddField(
            model_name='ae_actividadeconomica',
            name='porcentaje_maximo_ingresos',
            field=models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='este  impuesto no puede ser superior a este % de los ingresos brutos obtenidos en el mes', max_digits=22),
        ),
    ]
