# Generated by Django 4.2 on 2024-01-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0173_ae_actividadeconomica_alicuota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipologia',
            name='es_zona',
            field=models.BooleanField(default=True, help_text='True es indocar que es ZONA , si esl False es Categorizacion (ORDENANZA 2024)'),
        ),
    ]
