# Generated by Django 4.2 on 2024-01-19 18:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0174_tipologia_es_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='InmuebleValoracionTerreno2024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Area en m2', max_digits=22)),
                ('valor_unitario', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='valor_unitario', max_digits=22)),
                ('area_factor_ajuste', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Area en m2 del factor de ajuste', max_digits=22)),
                ('valor_ajustado', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Valor Ajustado', max_digits=22)),
                ('valor_total', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Valor Total', max_digits=22)),
                ('observaciones', models.TextField(blank=True, help_text='observaciones', null=True)),
                ('aplica', models.CharField(default='T', help_text='TERRENO', max_length=1)),
                ('fines_fiscales', models.ForeignKey(blank=True, help_text='fines_fiscales asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.finesfiscales')),
                ('forma_factor_ajuste', models.ForeignKey(blank=True, help_text='Forma del factor de ajuste', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.forma')),
                ('inmueble', models.ForeignKey(help_text='Id Inmueble asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.inmueble')),
                ('tipo', models.ForeignKey(blank=True, help_text='Tipo de Inmueble asociado para determinar si unifamiliar o multifamiliar', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipoinmueble')),
                ('tipologia', models.ForeignKey(blank=True, help_text='tipologia asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipologia')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleValoracionConstruccion2024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_utilizado', models.BooleanField(default=False, help_text='subutilizado si o no')),
                ('fecha_construccion', models.DateField(blank=True, help_text='fecha construccion', null=True)),
                ('area', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Area en m2', max_digits=22)),
                ('valor', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='valor', max_digits=22)),
                ('depreciacion', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='depreciacion', max_digits=22)),
                ('valor_actual', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='valor', max_digits=22)),
                ('aplica', models.CharField(default='C', help_text='CONSTRUCCION', max_length=1)),
                ('inmueblevaloracionterreno', models.ForeignKey(help_text='Id inmueble_terreno asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.inmueblevaloracionterreno2024')),
                ('tipo', models.ForeignKey(help_text='Tipo de Inmueble asociado para determinar si unifamiliar o multifamiliar', on_delete=django.db.models.deletion.PROTECT, to='backend.tipoinmueble')),
                ('tipologia', models.ForeignKey(help_text='tipologia asociado', on_delete=django.db.models.deletion.PROTECT, to='backend.tipologia')),
            ],
        ),
    ]
