# Generated by Django 4.2 on 2024-01-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0175_inmueblevaloracionterreno2024_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de Categorizacion Ordenanza 2024', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de la Categorizacion Ordenanza 2024', unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tipologia',
            name='es_zona',
        ),
    ]
