# Generated by Django 4.2 on 2024-01-24 09:58

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0176_categorizacion_remove_tipologia_es_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipologia_Categorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(help_text='Codigo de tipologia', unique=True)),
                ('descripcion', models.TextField(help_text='descripcion de tipologia')),
                ('tarifa', models.DecimalField(decimal_places=8, default=Decimal('0'), help_text='Tarifa o Alicuota', max_digits=22)),
                ('habilitado', models.BooleanField(default=True, help_text='Esta activo?')),
                ('observaciones', models.TextField(blank=True, help_text='observaciones en caso de no esar hablita por que cambio el valor a causa de una ordenanza nueva.', null=True)),
                ('FinesFiscales', models.BooleanField(default=False, help_text='True es para fines fiscales(para impresion de cedula catastral)')),
                ('categorizacion', models.ForeignKey(blank=True, help_text='Categorizacion !! Base para calculo', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.categorizacion')),
            ],
        ),
    ]
