# Generated by Django 4.2 on 2024-01-24 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0177_tipologia_categorizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueblevaloracionconstruccion2024',
            name='tipologia',
        ),
        migrations.RemoveField(
            model_name='inmueblevaloracionterreno2024',
            name='tipologia',
        ),
        migrations.AddField(
            model_name='inmueblevaloracionconstruccion2024',
            name='tipologia_categorizacion',
            field=models.ForeignKey(blank=True, help_text='tipologia asociado ORDENANZA 2024', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipologia_categorizacion'),
        ),
        migrations.AddField(
            model_name='inmueblevaloracionterreno2024',
            name='tipologia_categorizacion',
            field=models.ForeignKey(blank=True, help_text='tipologia asociado ORDENANZA 2024', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipologia_categorizacion'),
        ),
    ]
