# Generated by Django 4.2 on 2024-01-25 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0178_remove_inmueblevaloracionconstruccion2024_tipologia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='categorizacion',
            field=models.ForeignKey(blank=True, help_text='Categorizacion !! Base para calculo', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.categorizacion'),
        ),
    ]
