# Generated by Django 4.2 on 2024-01-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0180_ic_impuestodescuento_tipologia_categorizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ae_patente',
            name='numero_documento_representante',
            field=models.TextField(help_text='Numero de documento (RIF)'),
        ),
        migrations.AlterField(
            model_name='tipologia_categorizacion',
            name='categorizacion',
            field=models.ForeignKey(blank=True, help_text='Categorizacion ORDENANZA 2024!! Base para calculo', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.categorizacion'),
        ),
    ]
