# Generated by Django 4.2 on 2024-02-07 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0181_alter_ae_patente_numero_documento_representante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ae_patente_actividadeconomica',
            name='AE_actividadeconomica',
            field=models.ForeignKey(blank=True, help_text='Id AE_ActividadEconomica', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ae_actividadeconomicadetalle'),
        ),
    ]
