# Generated by Django 4.2 on 2024-02-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0182_alter_ae_patente_actividadeconomica_ae_actividadeconomica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueblepropiedad',
            name='numero_documento',
            field=models.TextField(blank=True, help_text='Numero de expediente', null=True),
        ),
    ]
