# Generated by Django 4.2 on 2024-02-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0183_alter_inmueblepropiedad_numero_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='finaliza_flujo',
            field=models.BooleanField(default=False, help_text='Es TRUE si finaliza flujos'),
        ),
    ]
