# Generated by Django 4.2 on 2024-02-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0185_alter_conjuntoresidencial_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urbanizacion',
            options={'ordering': ['sector', 'nombre']},
        ),
        migrations.AlterUniqueTogether(
            name='urbanizacion',
            unique_together={('sector', 'nombre')},
        ),
        migrations.RemoveField(
            model_name='urbanizacion',
            name='codigo',
        ),
    ]
