# Generated by Django 4.2 on 2024-02-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0186_alter_urbanizacion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manzana',
            name='area',
        ),
        migrations.RemoveField(
            model_name='manzana',
            name='perimetro',
        ),
        migrations.RemoveField(
            model_name='manzana',
            name='via_este',
        ),
        migrations.RemoveField(
            model_name='manzana',
            name='via_norte',
        ),
        migrations.RemoveField(
            model_name='manzana',
            name='via_oeste',
        ),
        migrations.RemoveField(
            model_name='manzana',
            name='via_sur',
        ),
    ]
