# Generated by Django 4.2 on 2024-02-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0189_alter_parcela_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='codigo',
            field=models.TextField(blank=True, help_text='Codigo de la Parcela', null=True),
        ),
    ]
