# Generated by Django 4.2 on 2024-02-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0190_alter_parcela_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='codigo',
            field=models.TextField(help_text='Codigo de la Parcela'),
        ),
    ]
