# Generated by Django 4.2 on 2024-02-20 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0200_conjuntoresidencial_sector_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conjuntoresidencial',
            options={'ordering': ['sector', 'nombre']},
        ),
        migrations.AlterUniqueTogether(
            name='conjuntoresidencial',
            unique_together={('sector', 'nombre')},
        ),
    ]
