# Generated by Django 4.2 on 2024-02-21 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0201_alter_conjuntoresidencial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunidad', models.TextField(help_text='numero_civico de expediente', unique=True)),
                ('categoria', models.TextField(blank=True, help_text='numero_civico de expediente', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleCategorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_inmueble', models.TextField(help_text='numero_civico de expediente', unique=True)),
                ('tipo_inmueble', models.TextField(blank=True, help_text='numero_civico de expediente', null=True)),
                ('id_ambito', models.TextField(blank=True, help_text='numero_civico de expediente', null=True)),
                ('sector', models.TextField(blank=True, help_text='numero_civico de expediente', null=True)),
                ('id_manzana', models.TextField(blank=True, help_text='numero_civico de expediente', null=True)),
                ('id_parcela', models.TextField(blank=True, help_text='numero_civico de expediente', null=True)),
                ('id_sub_parcela', models.TextField(blank=True, help_text='numero_civico de expediente', null=True)),
                ('urb_barrio', models.TextField(blank=True, help_text='numero_civico de expediente', null=True)),
                ('con_residencial', models.TextField(blank=True, help_text='numero_civico de expediente', null=True)),
                ('edificio', models.TextField(blank=True, help_text='numero_civico de expediente', null=True)),
                ('avenida', models.TextField(blank=True, help_text='numero_civico de expediente', null=True)),
                ('via', models.TextField(blank=True, help_text='numero_civico de expediente', null=True)),
                ('referencia', models.TextField(blank=True, help_text='numero_civico de expediente', null=True)),
                ('telefono', models.TextField(blank=True, help_text='numero_civico de expediente', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='numero_civico de expediente', null=True)),
                ('direccion', models.TextField(blank=True, help_text='numero_civico de expediente', null=True)),
                ('total_construccion', models.TextField(blank=True, help_text='numero_civico de expediente', null=True)),
                ('total_terreno', models.TextField(help_text='numero_civico de expediente')),
                ('comunidad', models.ForeignKey(blank=True, help_text='comunidad', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.comunidad')),
            ],
        ),
    ]
