# Generated by Django 4.2 on 2024-03-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0204_remove_avenida_codigo_remove_calle_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoflujo',
            name='crea_expediente',
            field=models.BooleanField(default=False, help_text='genera un nuevo numero de expediente?'),
        ),
    ]
