# Generated by Django 4.2 on 2024-03-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0206_inmueble_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='imprime_recibo_entrega',
            field=models.BooleanField(default=False, help_text='Es TRUE si Imprime recibo de entrega a contribuyente (para expediente)'),
        ),
    ]
