# Generated by Django 4.2 on 2024-03-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0207_departamento_imprime_recibo_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flujodetalle',
            name='estado',
            field=models.CharField(choices=[('1', 'Pendiente por Recibir'), ('2', 'Recibido'), ('3', 'Pendiente por Procesar'), ('4', 'En proceso'), ('5', 'Proceso Culminado'), ('6', 'Pendiente por Enviar'), ('7', 'Enviado'), ('8', 'Finalizado'), ('9', 'Fin de la Solicitud'), ('0', 'Pendiente por Re-Enviar'), ('A', 'Imprimir Soporte Entrega Expediente')], default='1', help_text='Estado del proceso', max_length=1),
        ),
    ]
