# Generated by Django 4.2 on 2024-03-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0208_alter_flujodetalle_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujo',
            name='ReportePdf',
            field=models.FileField(blank=True, help_text='PDF soporte entrega de documentos', null=True, upload_to='FlujoEntregaDocumentos/'),
        ),
    ]
