# Generated by Django 4.2 on 2024-03-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0209_flujo_reportepdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='comunidad',
            field=models.ForeignKey(blank=True, help_text='comunidad', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.comunidad'),
        ),
    ]
