# Generated by Django 4.2 on 2024-03-25 15:01

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0213_historicalinmueblevaloracionterreno2024_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocuenta',
            name='ReportePdf',
            field=models.FileField(blank=True, help_text='PDF EstadoCuenta', null=True, upload_to=backend.models.estadocuenta_path),
        ),
        migrations.AlterField(
            model_name='flujo',
            name='ReportePdf',
            field=models.FileField(blank=True, help_text='PDF soporte entrega de documentos', null=True, upload_to=backend.models.flujoentrega_path),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='ReportePdfCedulaCatastral',
            field=models.FileField(blank=True, help_text='PDF Cedula catastral', null=True, upload_to=backend.models.immuebles_path_ficha),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='ReportePdfDesincorporacion',
            field=models.FileField(blank=True, help_text='PDF Desincorporacion', null=True, upload_to=backend.models.immuebles_path_desincopora),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='ReportePdf',
            field=models.FileField(blank=True, help_text='PDF PreFactura', null=True, upload_to=backend.models.liquidacion_path),
        ),
        migrations.AlterField(
            model_name='pagoestadocuenta',
            name='ReportePdf',
            field=models.FileField(blank=True, help_text='PDF PagoEstadoCuenta', null=True, upload_to=backend.models.pagoestadocuenta_path),
        ),
    ]
