# Generated by Django 4.2 on 2024-03-26 09:03

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0214_alter_estadocuenta_reportepdf_alter_flujo_reportepdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlativo',
            name='Logo1',
            field=models.ImageField(blank=True, help_text='Logo 1 para reporte', null=True, upload_to=backend.models.logos_path),
        ),
        migrations.AlterField(
            model_name='correlativo',
            name='Logo2',
            field=models.ImageField(blank=True, help_text='Logo 2 para reporte', null=True, upload_to=backend.models.logos_path),
        ),
    ]
