# Generated by Django 4.2 on 2024-04-09 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0216_alter_comunidad_clave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ic_impuestodescuento',
            name='inmueble',
            field=models.ForeignKey(blank=True, help_text='Inmueble', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.inmueble'),
        ),
    ]
