# Generated by Django 4.2 on 2024-04-12 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0217_ic_impuestodescuento_inmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacredito',
            name='anula_fecha',
            field=models.DateTimeField(blank=True, help_text='Fecha Anulacion', null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='anula_observaciones',
            field=models.TextField(blank=True, help_text='observaciones por la anulacion', null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='anula_usuario',
            field=models.TextField(blank=True, help_text='usuario que anula', null=True),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='habilitado',
            field=models.BooleanField(default=True, help_text='Esta activo?'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='motivoanulacionpago',
            field=models.ForeignKey(blank=True, help_text='ID MotivoAnulacionPago', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.motivoanulacionpago'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='observaciones',
            field=models.TextField(blank=True, help_text='observaciones', null=True),
        ),
    ]
