# Generated by Django 4.2 on 2024-04-22 10:07

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0218_notacredito_anula_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldocument',
            name='excel_file',
            field=models.FileField(upload_to=backend.models.excel_path),
        ),
    ]
