# Generated by Django 4.2 on 2024-04-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0219_alter_exceldocument_excel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldocument',
            name='excel_file2',
            field=models.FileField(blank=True, help_text='Nueva ruta', null=True, upload_to='excel_path/'),
        ),
    ]
