# Generated by Django 4.2 on 2024-04-22 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0221_remove_exceldocument_excel_file2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corridasbancarias',
            options={'ordering': ['bancocuenta', 'fecha', 'referencia', 'descripcion', 'monto']},
        ),
        migrations.AlterUniqueTogether(
            name='corridasbancarias',
            unique_together={('bancocuenta', 'fecha', 'referencia', 'descripcion', 'monto')},
        ),
    ]
