# Generated by Django 4.2 on 2024-04-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0222_alter_corridasbancarias_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corridasbancarias',
            name='fecha',
            field=models.DateTimeField(help_text='Fecha creacion'),
        ),
    ]
