# Generated by Django 4.2 on 2024-04-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0223_alter_corridasbancarias_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corridasbancarias',
            name='fecha',
            field=models.DateField(help_text='Fecha creacion'),
        ),
    ]
