# Generated by Django 4.2 on 2024-04-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0224_alter_corridasbancarias_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldocumentlog',
            name='codigo',
            field=models.TextField(help_text='id del registro con error'),
        ),
        migrations.AlterField(
            model_name='exceldocumentlog',
            name='error',
            field=models.TextField(help_text='codigo del error'),
        ),
        migrations.AlterField(
            model_name='exceldocumentlog',
            name='pestana',
            field=models.TextField(help_text='Pestaña del archivo de excel'),
        ),
    ]
