# Generated by Django 4.2 on 2024-05-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0225_alter_exceldocumentlog_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoflujo',
            name='aplica',
            field=models.CharField(choices=[('C', 'Inmuebles Urbanos'), ('I', 'Catastro'), ('A', 'Actividades económicas'), ('V', 'Vehiculos'), ('P', 'Propaganda y publicidad'), ('R', 'Recaudacion'), ('X', 'Todos')], default='X', help_text='A que tipo de sector aplica', max_length=1),
        ),
    ]
