# Generated by Django 4.2 on 2024-05-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0226_alter_tipoflujo_aplica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasamulta',
            name='aplica',
            field=models.CharField(choices=[('C', 'Inmuebles Urbanos'), ('I', 'Catastro'), ('A', 'Actividades económicas'), ('V', 'Vehiculos'), ('P', 'Propaganda y publicidad'), ('R', 'Recaudacion'), ('X', 'Todos')], default='X', help_text='A que tipo de sector aplica', max_length=1),
        ),
        migrations.AlterField(
            model_name='tasamulta',
            name='tipo',
            field=models.CharField(choices=[('I', 'Impuesto'), ('T', 'Tasa'), ('M', 'Multa'), ('R', 'Recaudacion'), ('O', 'Otro')], default='O', help_text='tipo de recaudacion', max_length=1),
        ),
    ]
