# Generated by Django 4.2 on 2024-05-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0228_tipopago_lstar_tipopago_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopago',
            name='operacion',
            field=models.TextField(blank=True, help_text='codigo Tipo de operacion', null=True),
        ),
    ]
