# Generated by Django 4.2 on 2024-07-09 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0229_alter_tipopago_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoestadocuenta',
            name='liquidacion',
            field=models.ForeignKey(blank=True, help_text='ID Cabecera liquidacion', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.liquidacion'),
        ),
    ]
