# Generated by Django 4.2 on 2024-09-12 11:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0230_alter_pagoestadocuenta_liquidacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='IC_ImpuestoExoneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Descripcion', unique=True)),
                ('fechadesde', models.DateField(blank=True, help_text='fecha Desde donde valida si aplica el descuento', null=True)),
                ('fechahasta', models.DateField(blank=True, help_text='fecha Hasta donde valida si aplica el descuento', null=True)),
                ('m2desde', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='M2 desde', max_digits=22, null=True)),
                ('m2hasta', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), help_text='m2 hasta', max_digits=22, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='Porcentaje de descuento', max_digits=22, null=True)),
                ('habilitado', models.BooleanField(default=True, help_text='Esta activo?')),
                ('multa', models.BooleanField(default=False, help_text='Considera la multa para la exoneracion')),
                ('recargo', models.BooleanField(default=False, help_text='Considera el recargo para la exoneracion')),
                ('interes', models.BooleanField(default=False, help_text='Considera el interes para la exoneracion')),
                ('aplica', models.CharField(choices=[('C', 'Inmuebles Urbanos'), ('A', 'Actividades económicas'), ('V', 'Vehiculos'), ('P', 'Propaganda y publicidad'), ('X', 'Todos')], default='X', help_text='A que tipo de sector aplica', max_length=1)),
                ('inmueble', models.ForeignKey(blank=True, help_text='Inmueble', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.inmueble')),
                ('tipologia', models.ForeignKey(blank=True, help_text='tipologia asociado. Solo para Inmuebles. Si no tiene aplica a cualquier uso', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipologia')),
                ('tipologia_categorizacion', models.ForeignKey(blank=True, help_text='tipologia asociado. Solo para Inmuebles. Si no tiene aplica a cualquier uso', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipologia_categorizacion')),
            ],
        ),
        migrations.CreateModel(
            name='IC_ImpuestoDetalleExoneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(blank=True, help_text='Año de proceso', null=True)),
                ('base', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='Base de calculo', max_digits=22, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='Porcentaje de descuento', max_digits=22, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=8, default=Decimal('0'), help_text='Total. Segun la tipologia:IC_ImpuestoDetalle.base * TC_ImpuestoDescuentos.porcentaje', max_digits=22, null=True)),
                ('IC_impuesto', models.ForeignKey(blank=True, help_text='ID IC_Impuesto', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ic_impuesto')),
                ('IC_impuestoexoneracion', models.ForeignKey(blank=True, help_text='ID Impuesto Inmueble', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ic_impuestoexoneracion')),
                ('periodo', models.ForeignKey(blank=True, help_text='Periodo de proceso', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.ic_periodo')),
                ('tipologia', models.ForeignKey(blank=True, help_text='tipologia asociado', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.tipologia')),
            ],
        ),
    ]
