# Generated by Django 4.2 on 2024-10-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0231_ic_impuestoexoneracion_ic_impuestodetalleexoneracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='corridasbancarias',
            name='habilitado',
            field=models.BooleanField(default=True, help_text='Si esta habiltado quiere decir que NO se ha liquido en contabilidad como Ingreso No Liquidado'),
        ),
        migrations.AddField(
            model_name='corridasbancarias',
            name='referencia_complemento',
            field=models.TextField(blank=True, help_text='referencia complementaria (en caso de repetirse se complementa)', null=True),
        ),
    ]
