# Generated by Django 4.2 on 2024-10-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0233_correlativo_numero_referencia_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoestadocuentadetalle',
            name='nro_descripcion',
            field=models.TextField(blank=True, help_text='descripcion d ela trasferencia (esto se toma del extracto bancario', null=True),
        ),
        migrations.AddField(
            model_name='pagoestadocuentadetalle',
            name='nro_referencia2',
            field=models.TextField(blank=True, help_text='numero de referencia complementaria - cuando se repite (debito, trasferencia y nota de credito)', null=True),
        ),
    ]
