# Generated by Django 4.2 on 2024-10-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0234_pagoestadocuentadetalle_nro_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoestadocuentadetalle',
            name='observaciones',
            field=models.TextField(blank=True, help_text='observaciones', null=True),
        ),
    ]
