# Generated by Django 4.2 on 2024-10-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0235_pagoestadocuentadetalle_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='corridasbancarias',
            name='observaciones',
            field=models.TextField(blank=True, help_text='observaciones.', null=True),
        ),
        migrations.AlterField(
            model_name='flujodetalle',
            name='flujo',
            field=models.ForeignKey(help_text='ID FLUJO', on_delete=django.db.models.deletion.PROTECT, to='backend.flujo'),
        ),
        migrations.AlterField(
            model_name='pagoestadocuenta',
            name='observaciones',
            field=models.TextField(blank=True, help_text='observaciones. Aca se coloca el titulo del cuadre de caja cuando se hagan por ejempplo liquidaciones de transferencias de contribuyentes no recaudadas', null=True),
        ),
    ]
