# Generated by Django 4.2 on 2024-10-31 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0237_pagoestadocuentadetalle_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoestadocuentadetalle',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='pagoestadocuentadetalle',
            name='fecha',
        ),
    ]
