# Generated by Django 4.2 on 2024-10-31 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0238_remove_pagoestadocuentadetalle_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoestadocuentadetalle',
            name='corridasbancarias',
            field=models.ForeignKey(blank=True, help_text='ID CorridaBancaria', null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.corridasbancarias'),
        ),
    ]
