# Generated by Django 4.2 on 2024-11-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0239_pagoestadocuentadetalle_corridasbancarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasamulta',
            name='utiliza_m2',
            field=models.BooleanField(default=False, help_text='si True utiliza m2, pra catastro lo busca de la valoracion economica'),
        ),
    ]
